<div style="display: flex; background-color: #3F579F;">
    <h1 style="margin: auto; font-weight: bold; padding: 30px 30px 0px 30px;" align="center">Consumption needs of buildings - Project 4</h1>
</div>
<div style="display: flex; background-color: #3F579F; margin: auto; padding: 5px 30px 0px 30px;" >
    <h2 style="width: 100%; text-align: center; float: left;" align="center">| Analysis notebook |</h2>
</div>
<div style="display: flex; background-color: #3F579F; margin: auto; padding: 10px 30px 30px 30px;">
    <h3 style="width: 100%; text-align: center; font-size:26px; float: left;" align="center">Data Scientist course - OpenClassrooms</h3>
</div>

<div style="background-color: #506AB9;" >
    <h3 style="margin: auto; padding: 20px; color:#fff; ">1. Libraries and functions</h3>
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">1.1. Libraries and functions</h3>
</div>

In [1]:
import io
import gc
import ast
import datetime
from math import prod
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.gofplots import qqplot
from sklearn.preprocessing import StandardScaler
from sklearn import decomposition
from sklearn.decomposition import PCA


# import os
# import itertools
# import math
# import matplotlib.gridspec as gridspec
# from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
# from sklearn.model_selection import train_test_split
# from sklearn.impute import KNNImputer
# from sklearn.metrics import mean_squared_error, r2_score
# from sklearn.linear_model import LinearRegression



%matplotlib inline
sns.set_theme(style="darkgrid")

SUB = str.maketrans("0123456789", "₀₁₂₃₄₅₆₇₈₉")
SUP = str.maketrans("0123456789", "⁰¹²³⁴⁵⁶⁷⁸⁹")

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">1.2. Functions declaration</h4>
</div>

In [2]:
def df_analysis(df, name_df, *args, **kwargs):
    """
    Method used to analyze on the DataFrame.

    Parameters:
    -----------------
        df (pandas.DataFrame): Dataset to analyze
        name_df (str): Dataset name
        
        *args, **kwargs:
        -----------------
            columns (list): Dataframe keys in list format
            flag (str): Flag to show complete information about the dataset to analyse
                        "complete" shows all information about the dataset

    Returns:
    -----------------
        None. 
        Print the analysis on the Dataset. 
    """
    
    # Getting the variables
    columns = kwargs.get("columns", None)
    type_analysis = kwargs.get("type_analysis", None)
    
    ORDERING_COMPLETE = [
        "name", "type", "records", "unique", "# NaN", "% NaN", "mean", "min", "25%", "50%", "75%", "max", "std"
    ]
    
    # Calculating the memory usage based on dataframe.info()
    buf = io.StringIO()
    df.info(buf=buf)
    memory_usage = buf.getvalue().split('\n')[-2]
    
    if df.empty:
        print("The", name_df, "dataset is empty. Please verify the file.")
    else:
        empty_cols = [col for col in df.columns if df[col].isna().all()] # identifying empty columns
        df_rows_duplicates = df[df.duplicated()] #identifying full duplicates rows
        
        # Creating a dataset based on Type object and records by columns
        type_cols = df.dtypes.apply(lambda x: x.name).to_dict() 
        df_resume = pd.DataFrame(list(type_cols.items()), columns = ["name", "type"])
        df_resume["records"] = list(df.count())
        df_resume["# NaN"] = list(df.isnull().sum())
        df_resume["% NaN"] = list(((df.isnull().sum() / len(df.index))*100).round(2))
        
        print("\nAnalysis of", name_df, "dataset")
        print("--------------------------------------------------------------------")
        print("- Dataset shape:                 ", df.shape[0], "rows and", df.shape[1], "columns")
        print("- Total of NaN values:           ", df.isna().sum().sum())
        print("- Percentage of NaN:             ", round((df.isna().sum().sum() / prod(df.shape)) * 100, 2), "%")
        print("- Total of full duplicates rows: ", df_rows_duplicates.shape[0])
        print("- Total of empty rows:           ", df.shape[0] - df.dropna(axis="rows", how="all").shape[0]) if df.dropna(axis="rows", how="all").shape[0] < df.shape[0] else \
                    print("- Total of empty rows:            0")
        print("- Total of empty columns:        ", len(empty_cols))
        print("  + The empty column is:         ", empty_cols) if len(empty_cols) == 1 else \
                    print("  + The empty column are:         ", empty_cols) if len(empty_cols) >= 1 else None
        print("- Unique indexes:                ", df.index.is_unique)
        
        if columns is not None:
            print("\n- The key(s):", columns, "is not present multiple times in the dataframe.\n  It CAN be used as a primary key.") if df.size == df.drop_duplicates(columns).size else \
                print("\n- The key(s):", columns, "is present multiple times in the dataframe.\n  It CANNOT be used as a primary key.")
        
        if type_analysis == "summarized":
            print("\n")
        
        if type_analysis is None or type_analysis != "summarized":
            pd.set_option("display.max_rows", None) # show full of showing rows
            pd.set_option("display.max_columns", None) # show full of showing cols
            pd.set_option("display.max_colwidth", None) # show full width of showing cols
            pd.set_option("display.float_format", lambda x: "%.5f" % x) # show full content in cell    
            
            if type_analysis is None or type_analysis != "complete":
                print("\n- Type object and records by columns      (",memory_usage,")")
                print("--------------------------------------------------------------------")
            elif type_analysis == "complete":
                df_resume["unique"] = list(df.nunique())
                df_desc = pd.DataFrame(df.describe().T).reset_index()
                df_desc = df_desc.rename(columns={"index": "name"})
                df_resume = df_resume.merge(right=df_desc[["name", "mean", "min", "25%", "50%", "75%", "max", "std"]], on="name", how="left")
                df_resume = df_resume[ORDERING_COMPLETE]
                print("\n- Type object and records by columns      (",memory_usage,")")
                print("--------------------------------------------------------------------")
                
            display(df_resume.sort_values("records", ascending=False))
            
            pd.reset_option("display.max_rows") # reset max of showing rows
            pd.reset_option("display.max_columns") # reset max of showing cols
            pd.reset_option("display.max_colwidth") # reset width of showing cols
            pd.reset_option("display.float_format") # reset show full content in cell
            
        # deleting dataframe to free memory
        if type_analysis == "complete":
            del [[df_resume, df_desc]]
            gc.collect()
            df_resume, df_desc = (pd.DataFrame() for i in range(2))
        else:
            del df_resume
            gc.collect()
            df_resume = pd.DataFrame()


def comparing_columns_df():
    """
    Method used to identify columns that do not match between datasets

    Returns:
    -----------------
        df (pandas.DataFrame): Dataframe with columns that do not match
    """

    LIST_COL, LIST_ORIGIN = ([] for i in range(2))

    for col in data_2015.columns:
        if col not in list(data_2016.columns):
            LIST_COL.append(col)
            LIST_ORIGIN.append("data_2015")

    for col in data_2016.columns:
        if col not in list(data_2015.columns):
            LIST_COL.append(col)
            LIST_ORIGIN.append("data_2016")

    df = pd.DataFrame({
        "column": LIST_COL,
        "origin": LIST_ORIGIN
    })
    
    display(df.sort_values("column"))
    
    return df


def types_different():
    """
    Method used to identify the same columns with different dtypes

    Returns:
    -----------------
        None. 
        Print the tests on a new Dataset. 
    """
    
    COLS_2015, COLS_2016, LIST_COL_DIFFERENT, LIST_DTYPE_2015, LIST_DTYPE_2016 = [[] for i in range(5)]
    
    for col in data_2015.columns:
        if col not in list(df_columns_not_matches.loc[df_columns_not_matches["origin"]=="data_2015", "column"]):         
            COLS_2015.append(col)
    for col in data_2016.columns:
        if col not in list(df_columns_not_matches.loc[df_columns_not_matches["origin"]=="data_2016", "column"]):
            COLS_2016.append(col)
    
    for col_2015, col_2016 in zip(COLS_2015, COLS_2016):
        if data_2015[col_2015].dtype != data_2016[col_2016].dtype:
            LIST_COL_DIFFERENT.append(col_2015)
            LIST_DTYPE_2015.append(str(data_2015[col_2015].dtype))
            LIST_DTYPE_2016.append(str(data_2016[col_2016].dtype))
            
    df_types_different = pd.DataFrame({
                            "column": LIST_COL_DIFFERENT,
                            "2015": LIST_DTYPE_2015,
                            "2016": LIST_DTYPE_2016
                        })
    
    return display(df_types_different.sort_values("column"))
            
            
def normality_test(df):
    """
    Method used to make the normality test.

    Parameters:
    -----------------
        df (pandas.DataFrame): Dataset to analyze

    Returns:
    -----------------
        None. 
        Print the tests on a new Dataset. 
    """
    
    list_test = {
        "Shapiro-Wilk":stats.shapiro, "D’Agostino’s K^2":stats.normaltest,
        "Kolmogorov-Smirnov":stats.kstest
    }
    
    
    alpha = 0.05
    fail_to_reject_H = "Sample looks Gaussian (fail to reject H0)"
    reject_H = "Sample does not look Gaussian (reject H0)"
    
    variable, test_name, result, hypothesis = [[] for i in range(4)]
    
    for key, value in list_test.items():
    
        for col in df.columns:
            
            if df[col].dtypes == "float64":
                variable.append(col)
                test_name.append(key)
                
                if key == "Kolmogorov-Smirnov":
                    stat, p_value = value(df[col], cdf="norm")
                else:
                    stat, p_value = value(df[col])
                    
                result.append("Statistics=%.3f, p-value=%.3f" % (stat, p_value))
                hypothesis.append(fail_to_reject_H.translate(SUB)) if p_value > alpha else hypothesis.append(reject_H.translate(SUB))
                
    df_normality_test = pd.DataFrame({
                            "variable": variable,
                            "normality test": test_name, 
                            "result": result,
                            "hypothesis": hypothesis})
    
    display(df_normality_test)

<div style="background-color: #506AB9;" >
    <h3 style="margin: auto; padding: 20px; color:#fff; ">2. Importing files</h3>
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">2.1. Importing and preparing files</h4>
</div>

<div class="alert alert-block alert-info">
    Based on the <b>official site of Seattle Open Data</b>, we can see the dataset <b>metadata</b> to know all features
    
    <ul style="list-style-type: square;">
        <li><b>2015: https://data.seattle.gov/dataset/2015-Building-Energy-Benchmarking/h7rm-fz6m</b></li>
        <li><b>2016: https://data.seattle.gov/dataset/2016-Building-Energy-Benchmarking/2bpz-gwpy</b></li>
    </ul>  
    
    On the other hand, we get the means of <b>Energy Star Score</b>
    <ul style="list-style-type: square;">
        <li><b>Energy Star Score: https://www.energystar.gov/buildings/benchmark/analyze_benchmarking_results</b></li>
    </ul>  
</div>

In [3]:
data_2015 = pd.read_csv(r"datasets\2015-building-energy-benchmarking.csv")
data_2016 = pd.read_csv(r"datasets\2016-building-energy-benchmarking.csv")

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">2.2. Initial analysis</h4>
</div>

<div class="alert alert-block alert-info">
Making <b>the initial analysis</b>
</div>

In [4]:
df_analysis(data_2015, "data_2015")

Analysis of data_2015 dataset
--------------------------------------------------------------------
- Dataset shape:                  3340 rows and 47 columns
- Total of NaN values:            26512
- Percentage of NaN:              16.89 %
- Total of full duplicates rows:  0
- Total of empty rows:            0
- Total of empty columns:         0
- Unique indexes:                 True

- Type object and records by columns      ( memory usage: 1.2+ MB )
--------------------------------------------------------------------

,name,type,records,# NaN,% NaN
0,OSEBuildingID,int64,3340,0,0.00000
9,YearBuilt,int64,3340,0,0.00000
40,ComplianceStatus,object,3340,0,0.00000
1,DataYear,int64,3340,0,0.00000
14,PropertyGFABuilding(s),int64,3340,0,0.00000
13,PropertyGFAParking,int64,3340,0,0.00000
12,PropertyGFATotal,int64,3340,0,0.00000
10,NumberofBuildings,int64,3340,0,0.00000
46,Zip Codes,int64,3340,0,0.00000
8,Neighborhood,object,3340,0,0.00000
4,PropertyName,object,3340,0,0.00000
3,PrimaryPropertyType,object,3340,0,0.00000
2,BuildingType,object,3340,0,0.00000
7,CouncilDistrictCode,int64,3340,0,0.00000
6,Location,object,3340,0,0.00000
38,DefaultData,object,3339,1,0.03000
5,TaxParcelIdentificationNumber,object,3338,2,0.06000
45,SPD Beats,float64,3338,2,0.06000
43,Seattle Police Department Micro Community Policing Plan Areas,float64,3338,2,0.06000
11,NumberofFloors,float64,3332,8,0.24000
29,SiteEnergyUseWN(kBtu),float64,3330,10,0.30000
36,GHGEmissions(MetricTonsCO2e),float64,3330,10,0.30000
35,OtherFuelUse(kBtu),float64,3330,10,0.30000
34,NaturalGas(kBtu),float64,3330,10,0.30000
33,NaturalGas(therms),float64,3330,10,0.30000
32,Electricity(kBtu),float64,3330,10,0.30000
31,Electricity(kWh),float64,3330,10,0.30000
30,SteamUse(kBtu),float64,3330,10,0.30000
37,GHGEmissionsIntensity(kgCO2e/ft2),float64,3330,10,0.30000
28,SiteEnergyUse(kBtu),float64,3330,10,0.30000
27,SourceEUIWN(kBtu/sf),float64,3330,10,0.30000
26,SourceEUI(kBtu/sf),float64,3330,10,0.30000
25,SiteEUIWN(kBtu/sf),float64,3330,10,0.30000
24,SiteEUI(kBtu/sf),float64,3330,10,0.30000
15,ListOfAllPropertyUseTypes,object,3213,127,3.80000
16,LargestPropertyUseType,object,3204,136,4.07000
17,LargestPropertyUseTypeGFA,float64,3204,136,4.07000
23,ENERGYSTARScore,float64,2560,780,23.35000
19,SecondLargestPropertyUseTypeGFA,float64,1559,1781,53.32000
18,SecondLargestPropertyUseType,object,1559,1781,53.32000
20,ThirdLargestPropertyUseType,object,560,2780,83.23000
21,ThirdLargestPropertyUseTypeGFA,float64,560,2780,83.23000
42,2010 Census Tracts,float64,224,3116,93.29000
44,City Council Districts,float64,213,3127,93.62000
22,YearsENERGYSTARCertified,object,110,3230,96.71000
41,Outlier,object,84,3256,97.49000
39,Comment,object,13,3327,99.61000

In [5]:
df_analysis(data_2016, "data_2016")

Analysis of data_2016 dataset
--------------------------------------------------------------------
- Dataset shape:                  3376 rows and 46 columns
- Total of NaN values:            19952
- Percentage of NaN:              12.85 %
- Total of full duplicates rows:  0
- Total of empty rows:            0
- Total of empty columns:         1
  + The empty column is:          ['Comments']
- Unique indexes:                 True

- Type object and records by columns      ( memory usage: 1.2+ MB )
--------------------------------------------------------------------

                               name     type  records  # NaN     % NaN
0                     OSEBuildingID    int64     3376      0   0.00000
11                     Neighborhood   object     3376      0   0.00000
1                          DataYear    int64     3376      0   0.00000
40                      DefaultData     bool     3376      0   0.00000
42                 ComplianceStatus   object     3376      0   0.00000
19           PropertyGFABuilding(s)    int64     3376      0   0.00000
18               PropertyGFAParking    int64     3376      0   0.00000
17                 PropertyGFATotal    int64     3376      0   0.00000
14                        YearBuilt    int64     3376      0   0.00000
13                        Longitude  float64     3376      0   0.00000
12                         Latitude  float64     3376      0   0.00000
16                   NumberofFloors    int64     3376      0   0.00000
10              CouncilDistrictCode    int64     3376      0   0.00000
4                      PropertyName   object     3376      0   0.00000
2                      BuildingType   object     3376      0   0.00000
9     TaxParcelIdentificationNumber   object     3376      0   0.00000
3               PrimaryPropertyType   object     3376      0   0.00000
7                             State   object     3376      0   0.00000
6                              City   object     3376      0   0.00000
5                           Address   object     3376      0   0.00000
33              SiteEnergyUse(kBtu)  float64     3371      5   0.15000
34            SiteEnergyUseWN(kBtu)  float64     3370      6   0.18000
30               SiteEUIWN(kBtu/sf)  float64     3370      6   0.18000
29                 SiteEUI(kBtu/sf)  float64     3369      7   0.21000
15                NumberofBuildings  float64     3368      8   0.24000
32             SourceEUIWN(kBtu/sf)  float64     3367      9   0.27000
44                TotalGHGEmissions  float64     3367      9   0.27000
38               NaturalGas(therms)  float64     3367      9   0.27000
37                Electricity(kBtu)  float64     3367      9   0.27000
36                 Electricity(kWh)  float64     3367      9   0.27000
35                   SteamUse(kBtu)  float64     3367      9   0.27000
39                 NaturalGas(kBtu)  float64     3367      9   0.27000
45            GHGEmissionsIntensity  float64     3367      9   0.27000
31               SourceEUI(kBtu/sf)  float64     3367      9   0.27000
20        ListOfAllPropertyUseTypes   object     3367      9   0.27000
8                           ZipCode  float64     3360     16   0.47000
22        LargestPropertyUseTypeGFA  float64     3356     20   0.59000
21           LargestPropertyUseType   object     3356     20   0.59000
28                  ENERGYSTARScore  float64     2533    843  24.97000
24  SecondLargestPropertyUseTypeGFA  float64     1679   1697  50.27000
23     SecondLargestPropertyUseType   object     1679   1697  50.27000
26   ThirdLargestPropertyUseTypeGFA  float64      596   2780  82.35000
25      ThirdLargestPropertyUseType   object      596   2780  82.35000
27         YearsENERGYSTARCertified   object      119   3257  96.48000
43                          Outlier   object       32   3344  99.05000
41                         Comments  float64        0   3376 100.00000

<div style="background-color: #506AB9;" >
    <h3 style="margin: auto; padding: 20px; color:#fff; ">3. Cleaning</h3>
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">3.1. Formatting columns in both datasets</h4>
</div>

<div class="alert alert-block alert-info">
    We are going to <b>concatenate both datasets</b> and keeping only the <b>unique values</b>. But first, we must know deeply the datastes.
</div>
<div class="alert alert-block alert-info">
    Based on the <b>official site of Seattle Open Data</b>, we can <b>identify similar features</b> between datasets
    
     <ul style="list-style-type: square;">
        <li><b>GHGEmissions(MetricTonsCO2e)</b> in <b>data_2015</b> is the same feature as <b>TotalGHGEmissions</b> in <b>data_2016</b></li>
        <li><b>GHGEmissionsIntensity(kgCO2e/ft2)</b> in <b>data_2015</b> is the same feature as <b>GHGEmissionsIntensity</b> in <b>data_2016</b></li>
    </ul>
    
     On the other hands, we have the following
    <ul style="list-style-type: square;">
        <li><b>Zip Codes</b> in <b>data_2015</b> is the same feature as <b>ZipCode</b> in <b>data_2016</b></li>
    </ul>
</div>

In [6]:
data_2015["ZipCode"] = data_2015["Zip Codes"]
data_2016["GHGEmissionsIntensity(kgCO2e/ft2)"] = data_2016["GHGEmissionsIntensity"]
data_2016["GHGEmissions(MetricTonsCO2e)"] = data_2016["TotalGHGEmissions"]

data_2015.drop(labels=["Zip Codes"], axis=1, inplace=True)
data_2016.drop(labels=["GHGEmissionsIntensity", "TotalGHGEmissions"], axis=1, inplace=True)

<div class="alert alert-block alert-info">
    Splitting the featured <b>Location</b> in <b>data_2015</b>
</div>

In [7]:
df_temp = data_2015["Location"].apply(lambda x: ast.literal_eval(x))
data_2015[["Latitude", "Longitude", "Address"]] = df_temp.apply(pd.Series)

<div class="alert alert-block alert-info">
<b>Comparing</b> the match between columns <b>before</b> making the <b>concatenation</b>
</div>

In [8]:
df_columns_not_matches = comparing_columns_df()

                                              column     origin
3                                 2010 Census Tracts  data_2015
7                                               City  data_2016
5                             City Council Districts  data_2015
2                                            Comment  data_2015
9                                           Comments  data_2016
0                                           Location  data_2015
1                                 OtherFuelUse(kBtu)  data_2015
6                                          SPD Beats  data_2015
4  Seattle Police Department Micro Community Poli...  data_2015
8                                              State  data_2016

<div class="alert alert-block alert-success">
    At this point, we get all columns that do <b>not match between the datasets</b>. Most of them seem not to have <b>importance</b> unlike <b>OtherFuelUse(kBtu)</b>
</div>

<div class="alert alert-block alert-info">
    <b>Eliminate</b> the columns that do not matched between the two datasets because they are not interesting for the mission<br>
    But, keeping the column <b>OtherFuelUse(kBtu)</b>
</div>

In [9]:
COLUMNS_NOT_MACTCH_2015 = list(df_columns_not_matches.loc[(df_columns_not_matches["origin"]=="data_2015") & (df_columns_not_matches["column"]!="OtherFuelUse(kBtu)"), "column"])
COLUMNS_NOT_MACTCH_2016 = list(df_columns_not_matches.loc[df_columns_not_matches["origin"]=="data_2016", "column"])

In [10]:
data_2015.drop(labels=COLUMNS_NOT_MACTCH_2015, axis=1, inplace=True)
data_2016.drop(labels=COLUMNS_NOT_MACTCH_2016, axis=1, inplace=True)

In [11]:
df_columns_not_matches = comparing_columns_df()

               column     origin
0  OtherFuelUse(kBtu)  data_2015

<div class="alert alert-block alert-info">
<b>Comparing</b> the types of each par of column <b>before</b> making the <b>concatenation</b>
    
</div>

In [12]:
data_2015 = data_2015.reindex(sorted(data_2015.columns), axis=1)
data_2016 = data_2016.reindex(sorted(data_2016.columns), axis=1)

In [13]:
types_different()

              column     2015     2016
0        DefaultData   object     bool
1           Latitude   object  float64
2          Longitude   object  float64
3  NumberofBuildings    int64  float64
4     NumberofFloors  float64    int64
5            ZipCode    int64  float64

<div class="alert alert-block alert-info">
    <b>Fixing column types</b><br>
</div>

In [14]:
data_2015["DefaultData"] = data_2015["DefaultData"].astype("bool")
data_2015["Latitude"] = data_2015["Latitude"].astype("float64")
data_2015["Longitude"] = data_2015["Longitude"].astype("float64")

data_2016["NumberofBuildings"] = data_2016["NumberofBuildings"].fillna(0)
data_2016["NumberofBuildings"] = data_2016["NumberofBuildings"].astype("int64")

data_2015["NumberofFloors"] = data_2015["NumberofFloors"].fillna(0)
data_2015["NumberofFloors"] = data_2015["NumberofFloors"].astype("int64")

data_2016["ZipCode"] = data_2016["ZipCode"].fillna(0)
data_2016["ZipCode"] = data_2016["ZipCode"].astype("int64")

types_different()

Empty DataFrame
Columns: [column, 2015, 2016]
Index: []

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">3.2. Merging datasets considering duplicate buildings</h4>
</div>

<div class="alert alert-block alert-info">
    It is necessary to <b>identify</b> those buildings <b>duplicates and not</b> between both datasets
</div>

In [15]:
in_common = data_2015.merge(data_2016, on="OSEBuildingID")
in_2015 = data_2015[~data_2015["OSEBuildingID"].isin(data_2016["OSEBuildingID"])]
in_2016 = data_2016[~data_2016["OSEBuildingID"].isin(data_2015["OSEBuildingID"])]

In [16]:
in_common.shape[0]

3284

In [17]:
in_2015.shape[0]

56

In [18]:
in_2016.shape[0]

92

<div class="alert alert-block alert-info">
    We got the following:
    <ul style="list-style-type: square;">
        <li>There are <b>3284 duplicates between both datasets</b></li>
        <li>There are <b>56 buildings only in data_2015</b></li>
        <li>There are <b>92 buildings only in data_2016</b></li>
    </ul>
    So, we are going to treat the data as follows:
    <ul style="list-style-type: square;">
        <li>Selecting most <b>recent value</b> by <b>Year</b> for each <b>OSEBuildingID</b></li>
        <li>Concatenating <b>data that is not in both datasets</b></li>
    </ul>
</div>

In [19]:
data_temp = pd.concat([data_2015[data_2015["OSEBuildingID"].isin(data_2016["OSEBuildingID"])],\
                      data_2016[data_2016["OSEBuildingID"].isin(data_2015["OSEBuildingID"])]],\
                      ignore_index=True).reset_index(drop=True)

In [20]:
data_temp = data_temp.sort_values(["OSEBuildingID", "DataYear"], ascending=True).reset_index(drop=True)

In [21]:
data_temp.shape

(6568, 44)

In [22]:
pd.set_option("display.max_rows", None) # show full of showing rows
pd.set_option("display.max_columns", None) # show full of showing cols
pd.set_option("display.max_colwidth", None) # show full width of showing cols
pd.set_option("display.float_format", lambda x: "%.5f" % x) # show full content in cell

In [23]:
data_temp.head(3)

,Address,BuildingType,ComplianceStatus,CouncilDistrictCode,DataYear,DefaultData,ENERGYSTARScore,Electricity(kBtu),Electricity(kWh),GHGEmissions(MetricTonsCO2e),GHGEmissionsIntensity(kgCO2e/ft2),LargestPropertyUseType,LargestPropertyUseTypeGFA,Latitude,ListOfAllPropertyUseTypes,Longitude,NaturalGas(kBtu),NaturalGas(therms),Neighborhood,NumberofBuildings,NumberofFloors,OSEBuildingID,OtherFuelUse(kBtu),Outlier,PrimaryPropertyType,PropertyGFABuilding(s),PropertyGFAParking,PropertyGFATotal,PropertyName,SecondLargestPropertyUseType,SecondLargestPropertyUseTypeGFA,SiteEUI(kBtu/sf),SiteEUIWN(kBtu/sf),SiteEnergyUse(kBtu),SiteEnergyUseWN(kBtu),SourceEUI(kBtu/sf),SourceEUIWN(kBtu/sf),SteamUse(kBtu),TaxParcelIdentificationNumber,ThirdLargestPropertyUseType,ThirdLargestPropertyUseTypeGFA,YearBuilt,YearsENERGYSTARCertified,ZipCode
0,"{""address"": ""405 OLIVE WAY"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98101""}",NonResidential,Compliant,7,2015,True,65.00000,3686160.00000,1080307.00000,249.43000,2.64000,Hotel,88434.00000,47.61219,Hotel,-122.33800,1272388.00000,12724.00000,DOWNTOWN,1,12,1,0.00000,NaN,Hotel,88434,0,88434,MAYFLOWER PARK HOTEL,NaN,NaN,78.90000,80.30000,6981428.00000,7097539.00000,173.50000,175.10000,2023032.00000,659000030,NaN,NaN,1927,NaN,18081
1,405 Olive way,NonResidential,Compliant,7,2016,False,60.00000,3946027.00000,1156514.25000,249.98000,2.83000,Hotel,88434.00000,47.61220,Hotel,-122.33799,1276453.00000,12764.52930,DOWNTOWN,1,12,1,NaN,NaN,Hotel,88434,0,88434,Mayflower park hotel,NaN,NaN,81.70000,84.30000,7226362.50000,7456910.00000,182.50000,189.00000,2003882.00000,0659000030,NaN,NaN,1927,NaN,98101
2,"{""address"": ""724 PINE ST"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98101""}",NonResidential,Compliant,7,2015,True,51.00000,3905411.00000,1144563.00000,263.51000,2.38000,Hotel,83880.00000,47.61311,"Hotel, Parking, Restaurant",-122.33336,4448985.00000,44490.00000,DOWNTOWN,1,11,2,0.00000,NaN,Hotel,88502,15064,103566,PARAMOUNT HOTEL,Parking,15064.00000,94.40000,99.00000,8354235.00000,8765788.00000,191.30000,195.20000,0.00000,659000220,Restaurant,4622.00000,1996,NaN,18081

In [24]:
data_temp.shape[0]

6568

In [25]:
data_temp = data_temp.sort_values(["OSEBuildingID", "DataYear"])

In [26]:
data_temp.head(6)

,Address,BuildingType,ComplianceStatus,CouncilDistrictCode,DataYear,DefaultData,ENERGYSTARScore,Electricity(kBtu),Electricity(kWh),GHGEmissions(MetricTonsCO2e),GHGEmissionsIntensity(kgCO2e/ft2),LargestPropertyUseType,LargestPropertyUseTypeGFA,Latitude,ListOfAllPropertyUseTypes,Longitude,NaturalGas(kBtu),NaturalGas(therms),Neighborhood,NumberofBuildings,NumberofFloors,OSEBuildingID,OtherFuelUse(kBtu),Outlier,PrimaryPropertyType,PropertyGFABuilding(s),PropertyGFAParking,PropertyGFATotal,PropertyName,SecondLargestPropertyUseType,SecondLargestPropertyUseTypeGFA,SiteEUI(kBtu/sf),SiteEUIWN(kBtu/sf),SiteEnergyUse(kBtu),SiteEnergyUseWN(kBtu),SourceEUI(kBtu/sf),SourceEUIWN(kBtu/sf),SteamUse(kBtu),TaxParcelIdentificationNumber,ThirdLargestPropertyUseType,ThirdLargestPropertyUseTypeGFA,YearBuilt,YearsENERGYSTARCertified,ZipCode
0,"{""address"": ""405 OLIVE WAY"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98101""}",NonResidential,Compliant,7,2015,True,65.00000,3686160.00000,1080307.00000,249.43000,2.64000,Hotel,88434.00000,47.61219,Hotel,-122.33800,1272388.00000,12724.00000,DOWNTOWN,1,12,1,0.00000,NaN,Hotel,88434,0,88434,MAYFLOWER PARK HOTEL,NaN,NaN,78.90000,80.30000,6981428.00000,7097539.00000,173.50000,175.10000,2023032.00000,659000030,NaN,NaN,1927,NaN,18081
1,405 Olive way,NonResidential,Compliant,7,2016,False,60.00000,3946027.00000,1156514.25000,249.98000,2.83000,Hotel,88434.00000,47.61220,Hotel,-122.33799,1276453.00000,12764.52930,DOWNTOWN,1,12,1,NaN,NaN,Hotel,88434,0,88434,Mayflower park hotel,NaN,NaN,81.70000,84.30000,7226362.50000,7456910.00000,182.50000,189.00000,2003882.00000,0659000030,NaN,NaN,1927,NaN,98101
2,"{""address"": ""724 PINE ST"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98101""}",NonResidential,Compliant,7,2015,True,51.00000,3905411.00000,1144563.00000,263.51000,2.38000,Hotel,83880.00000,47.61311,"Hotel, Parking, Restaurant",-122.33336,4448985.00000,44490.00000,DOWNTOWN,1,11,2,0.00000,NaN,Hotel,88502,15064,103566,PARAMOUNT HOTEL,Parking,15064.00000,94.40000,99.00000,8354235.00000,8765788.00000,191.30000,195.20000,0.00000,659000220,Restaurant,4622.00000,1996,NaN,18081
3,724 Pine street,NonResidential,Compliant,7,2016,False,61.00000,3242851.00000,950425.18750,295.86000,2.86000,Hotel,83880.00000,47.61317,"Hotel, Parking, Restaurant",-122.33393,5145082.00000,51450.81641,DOWNTOWN,1,11,2,NaN,NaN,Hotel,88502,15064,103566,Paramount Hotel,Parking,15064.00000,94.80000,97.90000,8387933.00000,8664479.00000,176.10001,179.39999,0.00000,0659000220,Restaurant,4622.00000,1996,NaN,98101
4,"{""address"": ""1900 5TH AVE"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98101""}",NonResidential,Compliant,7,2015,True,18.00000,49762435.00000,14583930.00000,2061.48000,1.92000,Hotel,757243.00000,47.61335,"Hotel, Parking, Swimming Pool",-122.33770,3709900.00000,37099.00000,DOWNTOWN,1,41,3,0.00000,NaN,Hotel,961990,0,961990,WESTIN HOTEL,Parking,100000.00000,96.60000,99.70000,73130656.00000,75506272.00000,242.70000,246.50000,19660404.00000,659000475,Swimming Pool,0.00000,1969,NaN,18081
5,1900 5th Avenue,NonResidential,Compliant,7,2016,False,43.00000,49526664.00000,14515435.00000,2089.28000,2.19000,Hotel,756493.00000,47.61393,Hotel,-122.33810,1493800.00000,14938.00000,DOWNTOWN,1,41,3,NaN,NaN,Hotel,759392,196718,956110,5673-The Westin Seattle,NaN,NaN,96.00000,97.70000,72587024.00000,73937112.00000,241.89999,244.10001,21566554.00000,0659000475,NaN,NaN,1969,NaN,98101

In [29]:
data_temp["ComplianceStatus"].unique()

array(['Compliant', 'Error - Correct Default Data', 'Missing Data',
       'Non-Compliant', 'Not Compliant'], dtype=object)

In [33]:
data_temp.groupby("ComplianceStatus")["OSEBuildingID"].count().sort_values(ascending=False)

ComplianceStatus
Compliant                       6406
Error - Correct Default Data     110
Non-Compliant                     34
Missing Data                      15
Not Compliant                      3
Name: OSEBuildingID, dtype: int64

In [49]:
LIST_INITIAL = ["OSEBuildingID", "DataYear", "DefaultData", "ComplianceStatus"]
data_temp = data_temp[LIST_INITIAL + (list(set(data_temp.columns) - set(LIST_INITIAL)))]

In [52]:
data_temp[data_temp["ComplianceStatus"] == "Error - Correct Default Data"].sort_values(["OSEBuildingID", "DataYear"]).head(6)

,OSEBuildingID,DataYear,DefaultData,ComplianceStatus,ThirdLargestPropertyUseTypeGFA,SiteEnergyUseWN(kBtu),PropertyGFATotal,ListOfAllPropertyUseTypes,PropertyGFABuilding(s),GHGEmissions(MetricTonsCO2e),ENERGYSTARScore,Neighborhood,SourceEUI(kBtu/sf),BuildingType,CouncilDistrictCode,Electricity(kWh),Latitude,NaturalGas(kBtu),SiteEnergyUse(kBtu),YearBuilt,OtherFuelUse(kBtu),ZipCode,PrimaryPropertyType,NumberofFloors,ThirdLargestPropertyUseType,GHGEmissionsIntensity(kgCO2e/ft2),SourceEUIWN(kBtu/sf),Address,NumberofBuildings,Outlier,Electricity(kBtu),SiteEUIWN(kBtu/sf),SteamUse(kBtu),SecondLargestPropertyUseTypeGFA,YearsENERGYSTARCertified,NaturalGas(therms),SecondLargestPropertyUseType,TaxParcelIdentificationNumber,LargestPropertyUseType,PropertyName,Longitude,LargestPropertyUseTypeGFA,SiteEUI(kBtu/sf),PropertyGFAParking
45,28,2016,True,Error - Correct Default Data,NaN,1713623.50000,56228,K-12 School,56228,38.53000,95.00000,SOUTHEAST,60.70000,SPS-District K-12,2,274605.90630,47.54576,602523.00000,1539478.50000,1961,NaN,98118,K-12 School,2,NaN,0.69000,64.60000,5149 S. Graham St.,1,NaN,936955.00000,29.10000,0.00000,NaN,NaN,6025.22900,NaN,1102000138,K-12 School,Graham Hill Elementary,-122.26853,58916.00000,26.10000,0
61,36,2016,True,Error - Correct Default Data,NaN,7800349.50000,160645,K-12 School,160645,270.18000,75.00000,NORTH,68.10000,SPS-District K-12,5,570809.18750,47.70994,4831572.00000,6779173.00000,1949,NaN,98125,K-12 School,2,NaN,1.68000,75.70000,11051 34th Ave. N.E.,1,NaN,1947601.00000,47.50000,0.00000,NaN,NaN,48315.71875,NaN,0752000170,K-12 School,Jane Addams Middle,-122.29301,164229.00000,41.30000,0
75,51,2016,True,Error - Correct Default Data,NaN,7329817.50000,175565,K-12 School,175565,266.05000,88.00000,NORTHEAST,55.00000,SPS-District K-12,4,468840.50000,47.68252,4799443.00000,6399127.50000,1950,NaN,98115,K-12 School,2,NaN,1.52000,60.40000,3003 N.E. 75th St.,1,NaN,1599684.00000,40.10000,0.00000,NaN,NaN,47994.43359,NaN,0425049022,K-12 School,Eckstein Middle,-122.29498,182861.00000,35.00000,0
171,125,2016,True,Error - Correct Default Data,NaN,7300977.50000,130862,K-12 School,130862,238.48000,61.00000,GREATER DUWAMISH,85.60000,SPS-District K-12,2,663194.50000,47.56413,4193207.00000,6456026.00000,1957,NaN,98108,K-12 School,1,NaN,1.82000,93.50000,1600 Columbian Way S.,1,NaN,2262820.00000,54.30000,0.00000,NaN,NaN,41932.06641,NaN,1624049214,K-12 School,Mercer International Middle,-122.31208,134446.00000,48.00000,0
173,127,2016,True,Error - Correct Default Data,NaN,1749171.25000,59955,K-12 School,59955,20.48000,93.00000,SOUTHEAST,78.70000,SPS-District K-12,2,420989.40630,47.55478,196983.00000,1633399.37500,1989,NaN,98118,K-12 School,3,NaN,0.34000,83.00000,5215 46th Ave. S.,1,NaN,1436416.00000,29.20000,0.00000,NaN,NaN,1969.83252,NaN,1704900242,K-12 School,Orca K-8 School,-122.27596,59955.00000,27.20000,0
175,130,2016,True,Error - Correct Default Data,NaN,3216155.00000,93218,K-12 School,93218,84.75000,86.00000,MAGNOLIA / QUEEN ANNE,65.90000,SPS-District K-12,7,435743.81250,47.63683,1400634.00000,2887392.00000,1964,NaN,98119,K-12 School,2,NaN,0.91000,70.80000,1915 1st Ave. W.,1,NaN,1486758.00000,34.50000,0.00000,NaN,NaN,14006.33984,NaN,1794501220,K-12 School,McClure Middle,-122.35896,93218.00000,31.00000,0

In [54]:
data_temp[data_temp["OSEBuildingID"].isin([36, 28, 51, 125])].sort_values(["OSEBuildingID", "DataYear"])

,OSEBuildingID,DataYear,DefaultData,ComplianceStatus,ThirdLargestPropertyUseTypeGFA,SiteEnergyUseWN(kBtu),PropertyGFATotal,ListOfAllPropertyUseTypes,PropertyGFABuilding(s),GHGEmissions(MetricTonsCO2e),ENERGYSTARScore,Neighborhood,SourceEUI(kBtu/sf),BuildingType,CouncilDistrictCode,Electricity(kWh),Latitude,NaturalGas(kBtu),SiteEnergyUse(kBtu),YearBuilt,OtherFuelUse(kBtu),ZipCode,PrimaryPropertyType,NumberofFloors,ThirdLargestPropertyUseType,GHGEmissionsIntensity(kgCO2e/ft2),SourceEUIWN(kBtu/sf),Address,NumberofBuildings,Outlier,Electricity(kBtu),SiteEUIWN(kBtu/sf),SteamUse(kBtu),SecondLargestPropertyUseTypeGFA,YearsENERGYSTARCertified,NaturalGas(therms),SecondLargestPropertyUseType,TaxParcelIdentificationNumber,LargestPropertyUseType,PropertyName,Longitude,LargestPropertyUseTypeGFA,SiteEUI(kBtu/sf),PropertyGFAParking
44,28,2015,True,Compliant,NaN,1716043.00000,56228,K-12 School,56228,35.17000,96.00000,SOUTHEAST,59.20000,SPS-District K-12,2,267181.00000,47.54570,542600.00000,1454222.00000,1961,0.00000,18800,K-12 School,2,NaN,0.56000,63.90000,"{""address"": ""5101 S GRAHAM ST"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98118""}",1,NaN,911659.00000,29.60000,0.00000,NaN,NaN,5426.00000,NaN,1102000138,K-12 School,GRAHAM HILL ELEMENTARY SCHOOL (SPS-DISTRICT),-122.26858,58320.00000,25.10000,0
45,28,2016,True,Error - Correct Default Data,NaN,1713623.50000,56228,K-12 School,56228,38.53000,95.00000,SOUTHEAST,60.70000,SPS-District K-12,2,274605.90630,47.54576,602523.00000,1539478.50000,1961,NaN,98118,K-12 School,2,NaN,0.69000,64.60000,5149 S. Graham St.,1,NaN,936955.00000,29.10000,0.00000,NaN,NaN,6025.22900,NaN,1102000138,K-12 School,Graham Hill Elementary,-122.26853,58916.00000,26.10000,0
60,36,2015,True,Compliant,NaN,8362498.00000,160645,K-12 School,160645,260.37000,80.00000,NORTH,62.60000,SPS-District K-12,5,501058.00000,47.71011,4678100.00000,6387710.00000,1949,0.00000,19579,K-12 School,2,NaN,1.58000,77.20000,"{""address"": ""11031 34TH AVE NE"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98125""}",1,NaN,1709681.00000,50.90000,0.00000,NaN,NaN,46781.00000,NaN,752000170,K-12 School,JANE ADAMS JUNIOR HIGH (SPS-DISTRICT),-122.29379,164229.00000,38.90000,0
61,36,2016,True,Error - Correct Default Data,NaN,7800349.50000,160645,K-12 School,160645,270.18000,75.00000,NORTH,68.10000,SPS-District K-12,5,570809.18750,47.70994,4831572.00000,6779173.00000,1949,NaN,98125,K-12 School,2,NaN,1.68000,75.70000,11051 34th Ave. N.E.,1,NaN,1947601.00000,47.50000,0.00000,NaN,NaN,48315.71875,NaN,0752000170,K-12 School,Jane Addams Middle,-122.29301,164229.00000,41.30000,0
74,51,2015,True,Compliant,NaN,8317888.00000,175565,K-12 School,175565,258.67000,88.00000,NORTHEAST,53.60000,SPS-District K-12,4,457772.00000,47.68245,4665500.00000,6227419.00000,1950,0.00000,18792,K-12 School,2,NaN,1.44000,67.30000,"{""address"": ""3003 NE 75TH ST"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98115""}",1,NaN,1561983.00000,45.50000,0.00000,NaN,NaN,46655.00000,NaN,425049022,K-12 School,ECKSTEIN MIDDLE (SPS-DISTRICT),-122.29394,182861.00000,34.10000,0
75,51,2016,True,Error - Correct Default Data,NaN,7329817.50000,175565,K-12 School,175565,266.05000,88.00000,NORTHEAST,55.00000,SPS-District K-12,4,468840.50000,47.68252,4799443.00000,6399127.50000,1950,NaN,98115,K-12 School,2,NaN,1.52000,60.40000,3003 N.E. 75th St.,1,NaN,1599684.00000,40.10000,0.00000,NaN,NaN,47994.43359,NaN,0425049022,K-12 School,Eckstein Middle,-122.29498,182861.00000,35.00000,0
170,125,2015,True,Compliant,NaN,7508759.00000,130862,K-12 School,130862,211.49000,65.00000,GREATER DUWAMISH,81.30000,SPS-District K-12,2,630571.00000,47.56301,3699700.00000,5851209.00000,1957,0.00000,18388,K-12 School,1,NaN,1.55000,97.80000,"{""address"": ""1600 S COLUMBIAN WAY"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98108""}",1,NaN,2151598.00000,57.40000,0.00000,NaN,NaN,36997.00000,NaN,1624049214,K-12 School,MERCER JR HIGH SCHOOL (SPS-DISTRICT),-122.31121,132060.00000,44.70000,0
171,125,2016,True,Error - Correct Default Data,NaN,7300977.50000,130862,K-12 School,130862,238.48000,61.00000,GREATER DUWAMISH,85.60000,SPS-District K-12,2,663194.50000,47.56413,4193207.00000,6456026.00000,1957,NaN,98108,K-12 School,1,NaN,1.82000,93.50000,1600 Columbian Way S.,1,NaN,2262820.00000,54.30000,0.00000,NaN,NaN,41932.06641,NaN,1624049214,K-12 School,Mercer International Middle,-122.31208,134446.00000,48.00000,0

In [72]:
data_2016[data_2016["OSEBuildingID"].isin([36, 28, 51, 125])].sort_values(["OSEBuildingID", "DataYear"])

,Address,BuildingType,ComplianceStatus,CouncilDistrictCode,DataYear,DefaultData,ENERGYSTARScore,Electricity(kBtu),Electricity(kWh),GHGEmissions(MetricTonsCO2e),GHGEmissionsIntensity(kgCO2e/ft2),LargestPropertyUseType,LargestPropertyUseTypeGFA,Latitude,ListOfAllPropertyUseTypes,Longitude,NaturalGas(kBtu),NaturalGas(therms),Neighborhood,NumberofBuildings,NumberofFloors,OSEBuildingID,Outlier,PrimaryPropertyType,PropertyGFABuilding(s),PropertyGFAParking,PropertyGFATotal,PropertyName,SecondLargestPropertyUseType,SecondLargestPropertyUseTypeGFA,SiteEUI(kBtu/sf),SiteEUIWN(kBtu/sf),SiteEnergyUse(kBtu),SiteEnergyUseWN(kBtu),SourceEUI(kBtu/sf),SourceEUIWN(kBtu/sf),SteamUse(kBtu),TaxParcelIdentificationNumber,ThirdLargestPropertyUseType,ThirdLargestPropertyUseTypeGFA,YearBuilt,YearsENERGYSTARCertified,ZipCode
22,5149 S. Graham St.,SPS-District K-12,Error - Correct Default Data,2,2016,True,95.00000,936955.00000,274605.90630,38.53000,0.69000,K-12 School,58916.00000,47.54576,K-12 School,-122.26853,602523.00000,6025.22900,SOUTHEAST,1,2,28,NaN,K-12 School,56228,0,56228,Graham Hill Elementary,NaN,NaN,26.10000,29.10000,1539478.50000,1713623.50000,60.70000,64.60000,0.00000,1102000138,NaN,NaN,1961,NaN,98118
30,11051 34th Ave. N.E.,SPS-District K-12,Error - Correct Default Data,5,2016,True,75.00000,1947601.00000,570809.18750,270.18000,1.68000,K-12 School,164229.00000,47.70994,K-12 School,-122.29301,4831572.00000,48315.71875,NORTH,1,2,36,NaN,K-12 School,160645,0,160645,Jane Addams Middle,NaN,NaN,41.30000,47.50000,6779173.00000,7800349.50000,68.10000,75.70000,0.00000,0752000170,NaN,NaN,1949,NaN,98125
38,3003 N.E. 75th St.,SPS-District K-12,Error - Correct Default Data,4,2016,True,88.00000,1599684.00000,468840.50000,266.05000,1.52000,K-12 School,182861.00000,47.68252,K-12 School,-122.29498,4799443.00000,47994.43359,NORTHEAST,1,2,51,NaN,K-12 School,175565,0,175565,Eckstein Middle,NaN,NaN,35.00000,40.10000,6399127.50000,7329817.50000,55.00000,60.40000,0.00000,0425049022,NaN,NaN,1950,NaN,98115
86,1600 Columbian Way S.,SPS-District K-12,Error - Correct Default Data,2,2016,True,61.00000,2262820.00000,663194.50000,238.48000,1.82000,K-12 School,134446.00000,47.56413,K-12 School,-122.31208,4193207.00000,41932.06641,GREATER DUWAMISH,1,1,125,NaN,K-12 School,130862,0,130862,Mercer International Middle,NaN,NaN,48.00000,54.30000,6456026.00000,7300977.50000,85.60000,93.50000,0.00000,1624049214,NaN,NaN,1957,NaN,98108

In [73]:
data_2015[data_2015["OSEBuildingID"].isin([36, 28, 51, 125])].sort_values(["OSEBuildingID", "DataYear"])

,Address,BuildingType,ComplianceStatus,CouncilDistrictCode,DataYear,DefaultData,ENERGYSTARScore,Electricity(kBtu),Electricity(kWh),GHGEmissions(MetricTonsCO2e),GHGEmissionsIntensity(kgCO2e/ft2),LargestPropertyUseType,LargestPropertyUseTypeGFA,Latitude,ListOfAllPropertyUseTypes,Longitude,NaturalGas(kBtu),NaturalGas(therms),Neighborhood,NumberofBuildings,NumberofFloors,OSEBuildingID,OtherFuelUse(kBtu),Outlier,PrimaryPropertyType,PropertyGFABuilding(s),PropertyGFAParking,PropertyGFATotal,PropertyName,SecondLargestPropertyUseType,SecondLargestPropertyUseTypeGFA,SiteEUI(kBtu/sf),SiteEUIWN(kBtu/sf),SiteEnergyUse(kBtu),SiteEnergyUseWN(kBtu),SourceEUI(kBtu/sf),SourceEUIWN(kBtu/sf),SteamUse(kBtu),TaxParcelIdentificationNumber,ThirdLargestPropertyUseType,ThirdLargestPropertyUseTypeGFA,YearBuilt,YearsENERGYSTARCertified,ZipCode
22,"{""address"": ""5101 S GRAHAM ST"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98118""}",SPS-District K-12,Compliant,2,2015,True,96.00000,911659.00000,267181.00000,35.17000,0.56000,K-12 School,58320.00000,47.54570,K-12 School,-122.26858,542600.00000,5426.00000,SOUTHEAST,1,2,28,0.00000,NaN,K-12 School,56228,0,56228,GRAHAM HILL ELEMENTARY SCHOOL (SPS-DISTRICT),NaN,NaN,25.10000,29.60000,1454222.00000,1716043.00000,59.20000,63.90000,0.00000,1102000138,NaN,NaN,1961,NaN,18800
30,"{""address"": ""11031 34TH AVE NE"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98125""}",SPS-District K-12,Compliant,5,2015,True,80.00000,1709681.00000,501058.00000,260.37000,1.58000,K-12 School,164229.00000,47.71011,K-12 School,-122.29379,4678100.00000,46781.00000,NORTH,1,2,36,0.00000,NaN,K-12 School,160645,0,160645,JANE ADAMS JUNIOR HIGH (SPS-DISTRICT),NaN,NaN,38.90000,50.90000,6387710.00000,8362498.00000,62.60000,77.20000,0.00000,752000170,NaN,NaN,1949,NaN,19579
37,"{""address"": ""3003 NE 75TH ST"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98115""}",SPS-District K-12,Compliant,4,2015,True,88.00000,1561983.00000,457772.00000,258.67000,1.44000,K-12 School,182861.00000,47.68245,K-12 School,-122.29394,4665500.00000,46655.00000,NORTHEAST,1,2,51,0.00000,NaN,K-12 School,175565,0,175565,ECKSTEIN MIDDLE (SPS-DISTRICT),NaN,NaN,34.10000,45.50000,6227419.00000,8317888.00000,53.60000,67.30000,0.00000,425049022,NaN,NaN,1950,NaN,18792
86,"{""address"": ""1600 S COLUMBIAN WAY"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98108""}",SPS-District K-12,Compliant,2,2015,True,65.00000,2151598.00000,630571.00000,211.49000,1.55000,K-12 School,132060.00000,47.56301,K-12 School,-122.31121,3699700.00000,36997.00000,GREATER DUWAMISH,1,1,125,0.00000,NaN,K-12 School,130862,0,130862,MERCER JR HIGH SCHOOL (SPS-DISTRICT),NaN,NaN,44.70000,57.40000,5851209.00000,7508759.00000,81.30000,97.80000,0.00000,1624049214,NaN,NaN,1957,NaN,18388

In [55]:
data_XX = data_temp.copy()

In [59]:
 data_QQQQ = data_XX.replace("None", "").groupby("OSEBuildingID",as_index=False).last()

In [60]:
data_QQQQ.shape

(3284, 44)

In [68]:
# data_QQQQ.sort_values(["OSEBuildingID", "DataYear"]).head(2)
data_QQQQ[data_QQQQ["OSEBuildingID"] == 36].sort_values(["DataYear"])

,OSEBuildingID,DataYear,DefaultData,ComplianceStatus,ThirdLargestPropertyUseTypeGFA,SiteEnergyUseWN(kBtu),PropertyGFATotal,ListOfAllPropertyUseTypes,PropertyGFABuilding(s),GHGEmissions(MetricTonsCO2e),ENERGYSTARScore,Neighborhood,SourceEUI(kBtu/sf),BuildingType,CouncilDistrictCode,Electricity(kWh),Latitude,NaturalGas(kBtu),SiteEnergyUse(kBtu),YearBuilt,OtherFuelUse(kBtu),ZipCode,PrimaryPropertyType,NumberofFloors,ThirdLargestPropertyUseType,GHGEmissionsIntensity(kgCO2e/ft2),SourceEUIWN(kBtu/sf),Address,NumberofBuildings,Outlier,Electricity(kBtu),SiteEUIWN(kBtu/sf),SteamUse(kBtu),SecondLargestPropertyUseTypeGFA,YearsENERGYSTARCertified,NaturalGas(therms),SecondLargestPropertyUseType,TaxParcelIdentificationNumber,LargestPropertyUseType,PropertyName,Longitude,LargestPropertyUseTypeGFA,SiteEUI(kBtu/sf),PropertyGFAParking
30,36,2016,True,Error - Correct Default Data,NaN,7800349.50000,160645,K-12 School,160645,270.18000,75.00000,NORTH,68.10000,SPS-District K-12,5,570809.18750,47.70994,4831572.00000,6779173.00000,1949,0.00000,98125,K-12 School,2,None,1.68000,75.70000,11051 34th Ave. N.E.,1,None,1947601.00000,47.50000,0.00000,NaN,None,48315.71875,None,0752000170,K-12 School,Jane Addams Middle,-122.29301,164229.00000,41.30000,0

In [69]:
# data_temp.sort_values(["OSEBuildingID", "DataYear"]).head(4)
data_temp[data_temp["OSEBuildingID"] == 36].sort_values(["DataYear"])

,OSEBuildingID,DataYear,DefaultData,ComplianceStatus,ThirdLargestPropertyUseTypeGFA,SiteEnergyUseWN(kBtu),PropertyGFATotal,ListOfAllPropertyUseTypes,PropertyGFABuilding(s),GHGEmissions(MetricTonsCO2e),ENERGYSTARScore,Neighborhood,SourceEUI(kBtu/sf),BuildingType,CouncilDistrictCode,Electricity(kWh),Latitude,NaturalGas(kBtu),SiteEnergyUse(kBtu),YearBuilt,OtherFuelUse(kBtu),ZipCode,PrimaryPropertyType,NumberofFloors,ThirdLargestPropertyUseType,GHGEmissionsIntensity(kgCO2e/ft2),SourceEUIWN(kBtu/sf),Address,NumberofBuildings,Outlier,Electricity(kBtu),SiteEUIWN(kBtu/sf),SteamUse(kBtu),SecondLargestPropertyUseTypeGFA,YearsENERGYSTARCertified,NaturalGas(therms),SecondLargestPropertyUseType,TaxParcelIdentificationNumber,LargestPropertyUseType,PropertyName,Longitude,LargestPropertyUseTypeGFA,SiteEUI(kBtu/sf),PropertyGFAParking
60,36,2015,True,Compliant,NaN,8362498.00000,160645,K-12 School,160645,260.37000,80.00000,NORTH,62.60000,SPS-District K-12,5,501058.00000,47.71011,4678100.00000,6387710.00000,1949,0.00000,19579,K-12 School,2,NaN,1.58000,77.20000,"{""address"": ""11031 34TH AVE NE"", ""city"": ""SEATTLE"", ""state"": ""WA"", ""zip"": ""98125""}",1,NaN,1709681.00000,50.90000,0.00000,NaN,NaN,46781.00000,NaN,752000170,K-12 School,JANE ADAMS JUNIOR HIGH (SPS-DISTRICT),-122.29379,164229.00000,38.90000,0
61,36,2016,True,Error - Correct Default Data,NaN,7800349.50000,160645,K-12 School,160645,270.18000,75.00000,NORTH,68.10000,SPS-District K-12,5,570809.18750,47.70994,4831572.00000,6779173.00000,1949,NaN,98125,K-12 School,2,NaN,1.68000,75.70000,11051 34th Ave. N.E.,1,NaN,1947601.00000,47.50000,0.00000,NaN,NaN,48315.71875,NaN,0752000170,K-12 School,Jane Addams Middle,-122.29301,164229.00000,41.30000,0

<div class="alert alert-block alert-danger">
    <b>Flag position</b>
</div>

In [27]:
XXXXXXXXXXXXX

NameError: name 'XXXXXXXXXXXXX' is not defined

<div class="alert alert-block alert-info">
    Selecting most <b>recent value</b> by <b>Year</b> for each <b>OSEBuildingID</b>
</div>

In [ ]:
data = data_temp.groupby("OSEBuildingID", as_index=False).last()

In [ ]:
data.shape

In [ ]:
df_analysis(data, "data", columns="OSEBuildingID", type_analysis="summarized")

<div class="alert alert-block alert-info">
    Concatenating <b>data that is not in both datasets</b>
</div>

In [ ]:
data = pd.concat([data, in_2015, in_2016], ignore_index=True).reset_index(drop=True)

In [ ]:
df_analysis(data, "data", columns="OSEBuildingID", type_analysis="summarized")

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">3.3. Identifying and formatting categorical columns</h4>
</div>

<div class="alert alert-block alert-info">
    List of <b>categorical</b> columns
</div>

In [ ]:
list(set(data.columns) - set(data._get_numeric_data()))

In [ ]:
data[list(set(data.columns) - set(data._get_numeric_data()))].head(5)

<div class="alert alert-block alert-warning">
    <b>TaxParcelIdentificationNumber</b> is a <b>numeric</b> column instead of <b>categorical</b> column
</div>

<div class="alert alert-block alert-info">
    Now, we are going to verify the data in <b>categorical</b> columns
</div>

In [ ]:
for col in list(set(data.columns) - set(data._get_numeric_data())):
    print(col)
    display(data[col].unique())

<div class="alert alert-block alert-success">
    At this point, we get that all <b>categorical</b> columns have more than one type of value
</div>

<div class="alert alert-block alert-info">
    <b>Cleaning</b> data in the features
</div>

In [ ]:
data["ComplianceStatus"].replace("Non-Compliant", "Not Compliant", inplace=True)
data["ComplianceStatus"].replace("Missing Data", np.nan, inplace=True)
data["ComplianceStatus"].replace("Error - Correct Default Data", np.nan, inplace=True)

data["Neighborhood"].replace("Ballard", "BALLARD", inplace=True)
data["Neighborhood"].replace("Central", "CENTRAL", inplace=True)
data["Neighborhood"].replace("North", "NORTH", inplace=True)
data["Neighborhood"].replace("Delridge", "DELRIDGE", inplace=True)
data["Neighborhood"].replace("DELRIDGE NEIGHBORHOODS", "DELRIDGE", inplace=True)
data["Neighborhood"].replace("Northwest", "NORTHWEST", inplace=True)

data["PrimaryPropertyType"].replace("Restaurant\n", "Restaurant", inplace=True)
data["PrimaryPropertyType"].replace("Self-Storage Facility\n", "Self-Storage Facility", inplace=True)
data["PrimaryPropertyType"].replace("Distribution Center\n", "Distribution Center", inplace=True)
data["PrimaryPropertyType"].replace("Small- and Mid-Sized Office", "Small and Mid-Sized Office", inplace=True)
data["PrimaryPropertyType"].replace("Supermarket / Grocery Store", "Supermarket/Grocery Store", inplace=True)

<div class="alert alert-block alert-info">
    <b>Changing</b> the type of data <b>Neighborhood</b>
</div>

In [ ]:
for col in list(set(data.columns) - set(data._get_numeric_data())):
    if col != "TaxParcelIdentificationNumber":
        data[col] = data[col].astype("category")

In [ ]:
df_analysis(data, "data")

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">3.4. Filtering information</h4>
</div>

<div class="alert alert-block alert-info">
    Based on the mision, we are going to <b>filter</b> the <b>types of building</b> considering only <b>"non residential" buildings</b><br>
    First of all, we should know in which columns we must make focus
</div>

In [ ]:
LIST_PROPERTY_COLS = []

for col in data.columns:
    if "Property" in col or "Building" in col:
        LIST_PROPERTY_COLS.append(col)
        
LIST_PROPERTY_COLS

In [ ]:
data[LIST_PROPERTY_COLS].head(5)

<div class="alert alert-block alert-info">
    Based on <b>the percentage of missing-values</b> or the <b>amount of data</b> in each <b>categorical column</b>, we make focus on the following columns: 
    <ul style="list-style-type: square;">
        <li><b>BuildingType</b></li>
        <li><b>PrimaryPropertyType</b></li>
        <li><b>LargestPropertyUseType</b></li>
    </ul> 
</div>

<div class="alert alert-block alert-info">
    Filtering by <b>BuildingType</b> and <b>"non residential"</b> buildings
</div>

In [ ]:
list(data["BuildingType"].unique())

In [ ]:
data = pd.DataFrame(data[~data["BuildingType"].str.contains("family", case=False, na=False).any(level=0)])

In [ ]:
df_analysis(data, "data", type_analysis="summarized")

<div class="alert alert-block alert-info">
    Filtering by <b>PrimaryPropertyType</b> and <b>"non residential"</b> buildings
</div>

In [ ]:
list(data["PrimaryPropertyType"].unique())

In [ ]:
data = data[~data["PrimaryPropertyType"].isin(["Residence Hall", "Residence Hall/Dormitory", "Low-Rise Multifamily"])]

In [ ]:
df_analysis(data, "data", type_analysis="summarized")

<div class="alert alert-block alert-info">
    Filtering by <b>LargestPropertyUseType</b> and <b>"non residential"</b> buildings
</div>

In [ ]:
list(data["LargestPropertyUseType"].unique())

In [ ]:
data = data[~data["LargestPropertyUseType"].isin(["Other - Lodging/Residential", "Multifamily Housing", "Residence Hall/Dormitory"])]

In [ ]:
df_analysis(data, "data")

<div class="alert alert-block alert-success">
    At this point, we have <b>reduced the dataset</b> shape from <b>3432</b> to <b>1659</b>
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">3.5. Selecting the features</h4>
</div>

<div class="alert alert-block alert-info">
    Based on the <b>official site of Seattle Open Data</b>, we can see the dataset <b>metadata</b> to know all features
    
    <ul style="list-style-type: square;">
        <li><b>2015: https://data.seattle.gov/dataset/2015-Building-Energy-Benchmarking/h7rm-fz6m</b></li>
        <li><b>2016: https://data.seattle.gov/dataset/2016-Building-Energy-Benchmarking/2bpz-gwpy</b></li>
    </ul>  
    
    On the other hand, we get the means of <b>Energy Star Score</b>
    <ul style="list-style-type: square;">
        <li><b>Energy Star Score: https://www.energystar.gov/buildings/benchmark/analyze_benchmarking_results</b></li>
    </ul>  
       
    The <b>target variables</b> are:
    <ul style="list-style-type: square;">
        <li><b>SiteEnergyUse(kBtu):</b>The annual amount of energy consumed by the property from all sources of energy.</li>
        <li><b>GHGEmissions(MetricTonsCO2e):</b>The total amount of greenhouse gas emissions, including carbon dioxide, methane, and nitrous oxide gases released into the atmosphere as a result of energy consumption at the property, measured in metric tons of carbon dioxide equivalent. This calculation uses a GHG emissions factor from Seattle CIty Light's portfolio of generating resources. This uses Seattle City Light's 2015 emissions factor of 52.44 lbs CO2e/MWh. Enwave steam factor = 170.17 lbs CO2e/MMBtu. Gas factor sourced from EPA Portfolio Manager = 53.11 kg CO2e/MBtu.</li>
    </ul>  
</div>

In [ ]:
TARGET_VARIABLES = [
    "SiteEnergyUse(kBtu)", "GHGEmissions(MetricTonsCO2e)"
]

In [ ]:
OTHER_VARIABLE = [
    "ENERGYSTARScore"
]

In [ ]:
DECLARATIVE_DATA = [
    "OSEBuildingID", "BuildingType", "ComplianceStatus", "PrimaryPropertyType", "LargestPropertyUseType", "NumberofBuildings", "NumberofFloors",
    "LargestPropertyUseTypeGFA",  "PropertyGFABuilding(s)", "PropertyGFAParking", "PropertyGFATotal",  
     "DataYear", "YearBuilt", "Neighborhood", "PropertyName", "Address"     
]

In [ ]:
CONSUMPTION_VARIABLES = [
    "Electricity(kBtu)", "NaturalGas(kBtu)", "SiteEUI(kBtu/sf)", "SourceEUI(kBtu/sf)", "SteamUse(kBtu)", "OtherFuelUse(kBtu)"   
]

<div class="alert alert-block alert-success">
    <b>df_bebcs: Building Energy Benchmarking City of Seattled</b>
</div>

In [ ]:
df_bebcs = data[DECLARATIVE_DATA + CONSUMPTION_VARIABLES + OTHER_VARIABLE + TARGET_VARIABLES].copy()

In [ ]:
pd.set_option("display.max_rows", None) # show full of showing rows
pd.set_option("display.max_columns", None) # show full of showing cols
pd.set_option("display.max_colwidth", None) # show full width of showing cols

In [ ]:
df_bebcs[df_bebcs["SiteEnergyUse(kBtu)"] == 0].head(5)

In [ ]:
data_2016[data_2016["SiteEnergyUse(kBtu)"] == 0].shape

In [ ]:
df_analysis(df_bebcs, "df_bebcs", type_analysis="complete")

<div class="alert alert-block alert-info">
    Count the amount of <b>NumberofFloors</b> and <b>NumberofBuildings</b> with value of 0
</div>

In [ ]:
df_bebcs[df_bebcs["NumberofFloors"]==0].shape[0]

In [ ]:
df_bebcs[df_bebcs["NumberofBuildings"]==0].shape[0]

<div class="alert alert-block alert-success">
    At this point, <b>we can notice</b> the following:<br/>
        
    <ul style="list-style-type: square;">
        <li>There are some <b>negatives values</b></li>
        <li>There are <b>NumberofBuildings</b> and <b>NumberofFloors</b> with <b>0</b></li>
        <li><b>Each target variable </b>has <b>an observation</b> with <b>missing-values</b></li>
        <li>We can infer the age of the building if we work with the fields <b>YearBuilt</b> and <b>DataYear</b></li>
    </ul>  
    <b>To Do</b><br/>
    Due to that, we are going to consider the following <b>hypothesis</b>. 
    <ul style="list-style-type: square;">
        <li>In <b>this case</b> it is not possible to have <b>negative values</b>. So, we are going to <b>format</b> all dataframe with <b>absolute values</b></li>
        <li>We are going to <b>delete</b> the <b>target</b> variable observations with <b>missing-values</b></li>
        <li>There is not <b>NumberofBuildings</b> and <b>NumberofFloors</b> with value of <b>0</b>.<br></li>
        <ul style="list-style-type: disc;">
            <li>For <b>NumberofFloors</b> we are going to try to find this information on internet. <b>If it is not possible</b>. So, we are going to <b>replace</b> these values <b>by 1</b></li>
            <li>For <b>NumberofBuildings</b> we are going to <b>replace</b> these values <b>by 1</b></li>
        </ul>
    </ul>     
</div>

<div class="alert alert-block alert-info">
    <b>Formatting</b> all dataframe with <b>absolute values</b>.
</div>

In [ ]:
for col in set(df_bebcs._get_numeric_data()):
    df_bebcs[col] = df_bebcs[col].abs()

<div class="alert alert-block alert-info">
    We are going to <b>delete</b> the <b>target</b> variable observations with <b>missing-values</b>
</div>

In [ ]:
df_bebcs = pd.DataFrame(df_bebcs[df_bebcs[TARGET_VARIABLES].notnull().all(axis=1)]).reset_index(drop=True)

In [ ]:
df_analysis(df_bebcs, "df_bebcs", type_analysis="complete")

<div class="alert alert-block alert-info">
    There is not <b>NumberofBuildings</b> and <b>NumberofFloors</b> with value of <b>0</b>.<br>
    <ul style="list-style-type: square;">
        <li>For <b>NumberofFloors</b> we are going to try to find this information on internet. <b>If it is not possible</b>. So, we are going to <b>replace</b> these values <b>by 1</b></li>
        <li>For <b>NumberofBuildings</b> we are going to <b>replace</b> these values <b>by 1</b></li>
    </ul>
</div>

In [ ]:
df_bebcs.loc[df_bebcs["NumberofFloors"]==0, ["PrimaryPropertyType", "LargestPropertyUseType", "PropertyName", "Neighborhood", "Address", "NumberofFloors", "NumberofBuildings"]]

<div class="alert alert-block alert-info">
    <b>Details of buildings</b>
    <ul style="list-style-type: square;">
        <li><b>Grand Hyatt Seattle</b> [https://www.hyatt.com/en-US/hotel/washington/grand-hyatt-seattle/seagh]</li>
            <ul style="list-style-type: disc;">
               <li><b>Number of Buildings</b>: 1</li>
               <li><b>Number of Floors</b>: 30</li>
            </ul>
        <li><b>Arnold Pavilion</b> [https://seattle.medicaloffice.info/toc.cfm]</li>
            <ul style="list-style-type: disc;">
               <li><b>Number of Buildings</b>: 1</li>
               <li><b>Number of Floors</b>: 8</li>
            </ul>
        <li><b>2200 Westlake - SEDO</b> [https://www.northstarmeetingsgroup.com/Meeting-Event-Venues/Seattle/Convention-Hotel/Pan-Pacific-Seattle-p52565030]</li>
            <ul style="list-style-type: disc;">
               <li><b>Number of Buildings</b>: 4</li>
               <li><b>Number of Floors</b>: 11</li>
            </ul>
        <li><b>Pacific Place</b> [https://www.pacificplaceseattle.com/]</li>
            <ul style="list-style-type: disc;">
               <li><b>Number of Buildings</b>: 1</li>
               <li><b>Number of Floors</b>: 5</li>
               <li>Other information: It is a mall</li>
            </ul>
        <li><b>HART First Hill LLC</b> [https://www.swedish.org/locations/first-hill-campus/locations?page=2]</li>
            <ul style="list-style-type: disc;">
               <li><b>Number of Buildings</b>: 1</li>
               <li><b>Number of Floors</b>: 4</li>
            </ul>
        <li><b>University of Washington - Seattle Campus</b> [https://facilities.uw.edu/files/media/2019-04-02-uw-cmp-final-plan-reduced.pdf]</li>
            <ul style="list-style-type: disc;">
               <li><b>Number of Floors</b>: 14 in average</li>
            </ul>   
        <li><b>Smilow Rainier Vista Boys & Girls Club</b> [https://positiveplace.org/clubs/rainier-vista/]</li>
            <ul style="list-style-type: disc;">
               <li><b>Number of Floors</b>: 2</li>
            </ul>  
    </ul> 
</div>

In [ ]:
df_bebcs.loc[df_bebcs["PropertyName"]=="Grand Hyatt Seattle", "NumberofFloors"] = 30
df_bebcs.loc[df_bebcs["PropertyName"]=="Arnold Pavilion", "NumberofFloors"] = 8
df_bebcs.loc[df_bebcs["PropertyName"]=="2200 Westlake - SEDO", "NumberofFloors"] = 11
df_bebcs.loc[df_bebcs["PropertyName"]=="Pacific Place", "NumberofFloors"] = 5
df_bebcs.loc[df_bebcs["PropertyName"]=="HART First Hill LLC", "NumberofFloors"] = 4
df_bebcs.loc[df_bebcs["PropertyName"]=="University of Washington - Seattle Campus", "NumberofFloors"] = 14
df_bebcs.loc[df_bebcs["PropertyName"]=="Smilow Rainier Vista Boys & Girls Club", "NumberofFloors"] = 2

In [ ]:
df_bebcs.loc[df_bebcs["NumberofBuildings"]==0, "NumberofBuildings"] = 1

<div style="background-color: #506AB9;" >
    <h3 style="margin: auto; padding: 20px; color:#fff; ">4. Treating Outliers</h3>
</div>

<div class="alert alert-block alert-info">
    We are going to <b>treat </b> outliers only for variables <b>that are not targets</b>. Also, we are going to consider <b>PrimaryPropertyType</b> to treat the outliers.
    <ul style="list-style-type: square;">
        <li><b>LargestPropertyUseType</b></li>
        <li><b>PropertyGFABuilding(s)</b></li>
        <li><b>PropertyGFAParking</b></li>        
        <li><b>PropertyGFATotal</b></li>             
        <li><b>Electricity(kBtu)</b></li>
        <li><b>NaturalGas(kBtu)</b></li>
        <li><b>SiteEUI(kBtu/sf)</b></li>
        <li><b>SourceEUI(kBtu/sf)</b></li>
        <li><b>SteamUse(kBtu)</b></li>
        <li><b>OtherFuelUse(kBtu)</b></li>
        <li><b>SiteEnergyUse(kBtu)</b></li>
        <li><b>GHGEmissions(MetricTonsCO2e)</b></li>
    </ul>  
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">4.1. Treating Outliers with Z Score</h4>
</div>

<div class="alert alert-block alert-info">
    Deleting <b>outliers</b> with <b>Z Score</b>
</div>

In [ ]:
df_without_outliers = pd.DataFrame()

# List of features to be treated
LIST_FEATURES_TO_BE_TRAITED = [
    "LargestPropertyUseType", "PropertyGFABuilding(s)", "PropertyGFAParking", "PropertyGFATotal", "Electricity(kBtu)", 
    "NaturalGas(kBtu)", "SiteEUI(kBtu/sf)", "SourceEUI(kBtu/sf)", "SteamUse(kBtu)", "OtherFuelUse(kBtu)", 
    "SiteEnergyUse(kBtu)", "GHGEmissions(MetricTonsCO2e)"     
]

for property_type in df_bebcs["PrimaryPropertyType"].unique():
    
    # for each property type, we are going to define the max and min threshold to replace outliers
    df_temp_outliers = df_bebcs[df_bebcs["PrimaryPropertyType"] == property_type].copy()
    
    for col in set(df_temp_outliers._get_numeric_data()):
        
        if col in LIST_FEATURES_TO_BE_TRAITED:
            # Defining the Z Score
            df_temp_outliers[col + "_zscore"] = (df_temp_outliers[col] - df_temp_outliers[col].mean()) / df_temp_outliers[col].std()
            df_temp_outliers.loc[(df_temp_outliers[col + "_zscore"] > 3) | (df_temp_outliers[col + "_zscore"] < -3), col] = np.nan

            del df_temp_outliers[col + "_zscore"]
        
    df_without_outliers = pd.concat([df_without_outliers, df_temp_outliers])

In [ ]:
df_analysis(df_without_outliers, "df_without_outliers", type_analysis="complete")

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">4.2. Comparison of Outliers treatment</h4>
</div>

<div class="alert alert-block alert-info">
    Identifying the <b>PrimaryPropertyType</b> with more records to plot the comparison with <b>Z Score result</b>
</div>

In [ ]:
df_bebcs.groupby("PrimaryPropertyType")["OSEBuildingID"].count().sort_values(ascending=False).head(3)

<div class="alert alert-block alert-info">
    <b>Plotting</b> the comparison between data before and after treating <b>outliers</b> with <b>Z Score</b>
</div>

In [ ]:
LIST_FEATURES_TO_PLOTT = ["Electricity(kBtu)", "GHGEmissions(MetricTonsCO2e)"]
property_type = "Large Office"

df_temp = df_bebcs[df_bebcs["PrimaryPropertyType"] == property_type].copy()
df_temp_by_zscore = df_without_outliers[df_without_outliers["PrimaryPropertyType"] == property_type].copy()

for col in LIST_FEATURES_TO_PLOTT:

    # Creating a figure composed of two matplotlib.Axes objects (ax_box and ax_hist)
    fig, ((ax_box, ax_box_zscore), (ax_hist, ax_hist_zscore)) = \
                                                        plt.subplots(nrows=2, ncols=2, figsize=[14,8], sharex=True, gridspec_kw={"height_ratios": (.15, .85)})

    # Title for the complete RR078466118RUfigure
    fig.suptitle((col.capitalize() + " in " + property_type), fontsize="x-large", fontweight="bold", size=20)

    # Assigning a graph to each ax
    ax_box.title.set_text("Before treating outliers")
    ax_box_zscore.title.set_text("After zscore")

    sns.boxplot(data=df_temp, x=col, ax=ax_box)
    sns.boxplot(data=df_temp_by_zscore, x=col, ax=ax_box_zscore)

    sns.histplot(data=df_temp, x=col, kde=True, ax=ax_hist)
    sns.histplot(data=df_temp_by_zscore, x=col, kde=True, ax=ax_hist_zscore)

    # Remove x axis name for the boxplot
    ax_box.set(xlabel="")
    ax_box.set(yticks=[])
    ax_box_zscore.set(xlabel="")
    ax_box_zscore.set(yticks=[])

    plt.tight_layout()
    plt.savefig("img/outliers-" + (col[0:-5].capitalize()) + "-in-" + property_type + ".png")
    sns.despine(fig)

<div class="alert alert-block alert-success">
    Both percentiles and distributions appear similar
</div>

<div style="background-color: #6D83C5;" >
    <h3 style="margin: auto; padding: 20px; color:#fff; ">5. Add variables based on existing variables</h3>
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">5.1 Adding a building age variable </h4>
</div>

In [ ]:
df_without_outliers["BuildingAge"] = datetime.datetime.now().year - df_without_outliers["YearBuilt"]

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">5.2 Checking categories with few observations</h4>
</div>

In [ ]:
df_without_outliers.groupby("BuildingType")["OSEBuildingID"].count().sort_values(ascending=False)

In [ ]:
df_without_outliers.groupby("PrimaryPropertyType")["OSEBuildingID"].count().sort_values(ascending=False)

In [ ]:
df_without_outliers.groupby("LargestPropertyUseType")["OSEBuildingID"].count().sort_values(ascending=False)

<div class="alert alert-block alert-success">
    There are <b>categories with 0 observations</b>, so we are going to treat them to avoid this situation
</div>

<div class="alert alert-block alert-info">
    Groupinig by <b>PrimaryPropertyType</b> 
</div>

In [ ]:
PROPERTY_TYPE = df_without_outliers["PrimaryPropertyType"].unique().to_list()
PROPERTY_TYPE

In [ ]:
RENAME_PROPERTY_TYPE = [
    "Hotel", "Other", "Store/Restaurant", "Education", "Education", "Office", "Warehouse",
    "Warehouse", "Office", "Health", "Office", "Retail Store", "Health", "Warehouse", 
    "Other", "Retail Store", "Other", "Refrigerated Warehouse", "Store/Restaurant",
    "Warehouse", "Office"
]

In [ ]:
df_property_type_rename = pd.DataFrame({
    "PrimaryPropertyType" : PROPERTY_TYPE,
    "renamed_PrimaryPropertyType" : RENAME_PROPERTY_TYPE
})
df_property_type_rename

In [ ]:
df_without_outliers = df_without_outliers.merge(right=df_property_type_rename[["PrimaryPropertyType", "renamed_PrimaryPropertyType"]], on="PrimaryPropertyType", how="left")

In [ ]:
df_analysis(df_without_outliers, "df_without_outliers")

In [ ]:
df_without_outliers.groupby("renamed_PrimaryPropertyType")["OSEBuildingID"].count().sort_values(ascending=False)

<div class="alert alert-block alert-success">
    Now, we have <b>reduced the categories</b> ensuring that there are several observations for each type
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">5.3. Categories and their relationship with CO2 emissions</h4>
</div>

In [ ]:
for var in ["Neighborhood", "BuildingType", "renamed_PrimaryPropertyType", "PrimaryPropertyType", "LargestPropertyUseType"]:
    plt.figure(figsize=[12,10])
    sns.boxplot(x=df_without_outliers["GHGEmissions(MetricTonsCO2e)"], y=df_without_outliers[var], orient="h", showmeans=True, 
                meanprops={"markerfacecolor":"white", "markeredgecolor":"blue"})
    plt.title("CO2 emissions by " + var, size=20)
    plt.ylabel("CO2 emissions", size=14)
    plt.xlabel(var, size=14)
    plt.tight_layout()
    plt.savefig("img/comparison-of-GHGEmissions-in-" + var + ".png")
    plt.show()

# plt.figure(figsize=[12,10])
# sns.boxplot(y=df_without_outliers["GHGEmissions(MetricTonsCO2e)"], x=df_without_outliers["renamed_PrimaryPropertyType"], orient="v", showmeans=True, 
#             meanprops={"markerfacecolor":"white", "markeredgecolor":"blue"})
# plt.title("GHGEmissions(MetricTonsCO2e) in all categories", size=20)
# plt.ylabel("CO2 emissions", size=14)
# plt.xlabel("Property Type", size=14)
# plt.tight_layout()
# plt.savefig("img/comparison-of-GHGEmissions-in-each-category.png")
# plt.show()

<div class="alert alert-block alert-danger">
    <b>Flag Position</b>
</div>

In [ ]:
CCCCCCCCCCCCC

In [ ]:
df_bebcs.columns

<div class="alert alert-block alert-danger">
    <b>Fields to delete</b>
</div>

In [ ]:
"BuildingType", "PrimaryPropertyType", "LargestPropertyUseType", "DataYear", "PropertyName", "Address", 
"YearBuilt"

<div style="background-color: #6D83C5;" >
    <h3 style="margin: auto; padding: 20px; color:#fff; ">XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</h3>
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">5.1. Initial analysis</h4>
</div>

<div style="background-color: #6D83C5;" >
    <h5 style="margin: auto; padding: 20px; color:#fff; ">5.1.1 Primary Property type distribution</h5>
</div>

In [ ]:
data_piechart = df_without_outliers["renamed_PrimaryPropertyType"].sort_values(ascending=False).value_counts().values
labels_piechart = df_without_outliers["renamed_PrimaryPropertyType"].sort_values(ascending=False).value_counts().index.tolist()
textprops = dict(size=16, color="gray")
colors = ["#5975A4", "#CC8963", "#5F9E6E", "#AD5B5E", "#857AAB", "#7D6D5F", "#D095BF", "#EAEAF2", "#C1B37F"]
explode = (0, 0, 0, 0, 0, 0, 0, 0, 0)

In [ ]:
fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=[15,8])

fig.suptitle("Primary Property type distribution", size=25)

for lb, data, color in zip(labels_piechart, data_piechart, colors):
    ax2.bar(lb, data, label=lb, color=color)
for index, data in enumerate(data_piechart):
    plt.text(x=index, y=data+1 , s=f"{data}", horizontalalignment="center", fontdict=dict(fontsize=16, color="gray"))
ax2.set_title("by quantity (#)", fontsize=14)
ax2.axis('off')

ax1.pie(x=data_piechart, explode=explode, autopct="%1.1f%%", pctdistance=1.10, 
        textprops=textprops, colors=[color for color in colors], startangle=0)
ax1.set_title("by percentage (%)", fontsize=14)

fig.legend(labels_piechart, loc="center", ncol=5, fontsize=14, bbox_to_anchor=(0.5, -0.05), fancybox=True, shadow=True)

plt.tight_layout()
plt.savefig("img/primary-property-type-distribution.png")
plt.show()

In [ ]:
for col in list(set(data.columns) - set(data._get_numeric_data())):
    if col != "TaxParcelIdentificationNumber":
        print(data.groupby(col)["OSEBuildingID"].count().sort_values(ascending=False))
        print("________________________________________________________________________")

<div style="background-color: #506AB9;" >
    <h3 style="margin: auto; padding: 20px; color:#fff; ">5. Exploratory Data Analysis</h3>
</div>
<br>
<div class="alert alert-block alert-info">
    We are just going to make an <b>Exploraty Data Analysis</b> based on the following<b>target variables</b>
    <ul style="list-style-type: square;">
        <li><b>SiteEnergyUse(kBtu)</b></li>
        <li><b>GHGEmissions(MetricTonsCO2e)</b></li>
    </ul>  
</div>

In [ ]:
df_analysis(df_without_outliers, "df_without_outliers", type_analysis="complete")

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">5.1. Initial analysis</h4>
</div>

<div style="background-color: #6D83C5;" >
    <h5 style="margin: auto; padding: 20px; color:#fff; ">5.1.1 Primary Property type distribution</h5>
</div>

In [ ]:
data_piechart = df_without_outliers["renamed_PrimaryPropertyType"].sort_values(ascending=False).value_counts().values
labels_piechart = df_without_outliers["renamed_PrimaryPropertyType"].sort_values(ascending=False).value_counts().index.tolist()
textprops = dict(size=16, color="gray")
colors = ["#5975A4", "#CC8963", "#5F9E6E", "#AD5B5E", "#857AAB", "#7D6D5F", "#D095BF", "#EAEAF2", "#C1B37F"]
explode = (0, 0, 0, 0, 0, 0, 0, 0, 0)

In [ ]:
fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=[15,8])

fig.suptitle("Primary Property type distribution", size=25)

for lb, data, color in zip(labels_piechart, data_piechart, colors):
    ax2.bar(lb, data, label=lb, color=color)
for index, data in enumerate(data_piechart):
    plt.text(x=index, y=data+1 , s=f"{data}", horizontalalignment="center", fontdict=dict(fontsize=16, color="gray"))
ax2.set_title("by quantity (#)", fontsize=14)
ax2.axis('off')

ax1.pie(x=data_piechart, explode=explode, autopct="%1.1f%%", pctdistance=1.10, 
        textprops=textprops, colors=[color for color in colors], startangle=0)
ax1.set_title("by percentage (%)", fontsize=14)

fig.legend(labels_piechart, loc="center", ncol=5, fontsize=14, bbox_to_anchor=(0.5, -0.05), fancybox=True, shadow=True)

plt.tight_layout()
plt.savefig("img/primary-property-type-distribution.png")
plt.show()

<div style="background-color: #6D83C5;" >
    <h5 style="margin: auto; padding: 20px; color:#fff; ">5.1.2  Comparison of the targets variables in each Property type</h5>
</div>

In [ ]:
for var in TARGET_VARIABLES:
    if var != "ENERGYSTARScore":
        plt.figure(figsize=[12,10])
        sns.boxplot(x=df_without_outliers[var], y=df_without_outliers["renamed_PrimaryPropertyType"], orient="h", showmeans=True, 
                    meanprops={"markerfacecolor":"white", "markeredgecolor":"blue"})
        plt.title(var + " in all categories", size=20)
        plt.ylabel("Property Type", size=14)
        plt.xlabel("Quantity of " + var, size=14)
        plt.tight_layout()
        plt.savefig("img/comparison-of-" + var + "-in-each-category.png")
        plt.show()

<div class="alert alert-block alert-success">
    <b>Observations / Conclusions</b><br/><br/>
    Building related to <b>Health</b> have a high <b>SiteEnergyUse(kBtu)</b> and <b>GHGEmissions(MetricTonsCO2e)</b>
</div>

<div style="background-color: #6D83C5;" >
    <h5 style="margin: auto; padding: 20px; color:#fff; ">5.1.3  Comparison by Years</h5>
</div>

In [ ]:
fig, ax1 = plt.subplots(figsize=(20, 10))
sns.barplot(x="renamed_PrimaryPropertyType", 
            y="SiteEnergyUse(kBtu)", 
            hue="DataYear", 
            data=df_without_outliers)
plt.legend(bbox_to_anchor=(1.004, 1), borderaxespad=0, title="Years")
plt.ylabel("Site Energy Use (kBtu)", size=14)
plt.xlabel("Property Type", size=14)
plt.title("Site Energy Use by year in each property type", size=18)
plt.savefig("img\grouped-SiteEnergyUse-by-year.png")

In [ ]:
fig, ax1 = plt.subplots(figsize=(20, 10))
sns.barplot(x="renamed_PrimaryPropertyType", 
            y="GHGEmissions(MetricTonsCO2e)", 
            hue="DataYear", 
            data=df_without_outliers)
plt.legend(bbox_to_anchor=(1.004, 1), borderaxespad=0, title="Years")
plt.ylabel("Total GHG Emissions (MetricTonsCO2e)", size=14)
plt.xlabel("Property Type", size=14)
plt.title("Total GHG Emissions by year in each property type", size=18)
plt.savefig("img\grouped-GHGEmissions-by-year.png")

<div class="alert alert-block alert-success">
    <b>Observations / Conclusions</b><br/><br/>
    Building related to <b>Health</b> have a high <b>SiteEnergyUse(kBtu)</b> and <b>GHGEmissions(MetricTonsCO2e)</b>
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">5.2. Univariate analysis</h4>
</div>
<br>
<div class="alert alert-block alert-info">
    We are are going to plot the <b>not missing-values</b> of the following target values
    <ul style="list-style-type: square;">
        <li><b>SiteEnergyUse(kBtu)</b></li>
        <li><b>GHGEmissions(MetricTonsCO2e)</b></li>
    </ul>  
</div>

In [ ]:
# Filtering by non missing-values to can plot the QQplot
df_temp = pd.DataFrame(df_without_outliers[df_without_outliers[["SiteEnergyUse(kBtu)", "GHGEmissions(MetricTonsCO2e)"]].notnull().all(axis=1)])
        
for var in TARGET_VARIABLES:
    
    if var != "ENERGYSTARScore":

        fig = plt.figure(constrained_layout=True, figsize=[15,7])
        fig.suptitle(var, size=25, fontweight="bold", y=1.05)
        spec = fig.add_gridspec(nrows=2, ncols=2, width_ratios=[1, 1], height_ratios=[1, 5])

        ax_box = fig.add_subplot(spec[0, 0])
        ax_hist = fig.add_subplot(spec[1, 0])
        ax_qqplot = fig.add_subplot(spec[:, 1])

        # Boxplot
        boxplot = sns.boxplot(data=df_temp, x=df_temp[var], showmeans=True, ax=ax_box,
                              meanprops={"markerfacecolor":"white", "markeredgecolor":"blue"})
        ax_box.set(xlabel="", xticks=[])
        ax_box.set(yticks=[])
        boxplot.set_title("")

        # Histplot
        sns.histplot(data=df_temp, x=df_temp[var], bins=75,  kde=True,  ax=ax_hist)
        if var == "SiteEnergyUse(kBtu)":
            ax_hist.set(xlabel="kBtu")
        else:
            ax_hist.set(xlabel="MetricTonsCO2e")

        # QQplot
        qqplot(df_temp[var], line='s', ax=ax_qqplot)

        plt.savefig("img/qqplot-of-" + var + ".png")
        plt.show()

        print("\nMaking the Normality Test")
        print("---------------------------------")
        normality_test(df_temp[[var]])
        print("\n")

In [ ]:
pd.reset_option("display.max_colwidth") # reset width of showing cols

<div class="alert alert-block alert-success">
    <b>Observations / Conclusions</b>
    <ul style="list-style-type: square;">
        <li><b>SiteEnergyUse(kBtu)</b> and <b>GHGEmissions(MetricTonsCO2e)</b> do not have a <b>Normal distribution</b></li>
        <li>Based on the distribution plot, we notice that <b>all values are very close</b> what remains to be a problem</li>
    </ul>  
</div>

<div style="background-color: #6D83C5;" >
    <h5 style="margin: auto; padding: 20px; color:#fff; ">5.2.1 Log Normalization target variables</h5>
</div>
<br>
<div class="alert alert-block alert-info">
    Based on the <b>Univariate analysis</b> where we note that <b>SiteEnergyUse(kBtu)</b> and <b>GHGEmissions(MetricTonsCO2e)</b> do not have a <b>Normal distribution</b>
    and <b>all their values are very close</b> so, we are going to aplly the <b>Natural Logarithmic transformation</b> in these variables to get a <b>better Normal distribution</b> 
    of these values
</div>

In [ ]:
df_bebcs_log = df_without_outliers.copy()

<div class="alert alert-block alert-info">
    <b>To avoid missing-values</b>, we are going to apply <b>np.log(variable + 1)</b>
</div>

In [ ]:
df_bebcs_log["SiteEnergyUse(kBtu)_log"] = np.log(df_bebcs["SiteEnergyUse(kBtu)"] + 1)
df_bebcs_log["GHGEmissions(MetricTonsCO2e)_log"] = np.log(df_bebcs["GHGEmissions(MetricTonsCO2e)"] + 1)

In [ ]:
# Filtering by non missing-values to can plot the QQplot
df_temp = pd.DataFrame(df_bebcs_log[df_bebcs_log[["SiteEnergyUse(kBtu)", "SiteEnergyUse(kBtu)_log", "GHGEmissions(MetricTonsCO2e)", "GHGEmissions(MetricTonsCO2e)_log"]].notnull().all(axis=1)])
        
for var in ["SiteEnergyUse(kBtu)", "SiteEnergyUse(kBtu)_log", "GHGEmissions(MetricTonsCO2e)", "GHGEmissions(MetricTonsCO2e)_log"]:
    
    fig = plt.figure(constrained_layout=True, figsize=[14,7])
    fig.suptitle(var, size=25, fontweight="bold", y=1.05)
    spec = fig.add_gridspec(nrows=2, ncols=2, width_ratios=[1, 1], height_ratios=[1, 5])

    ax_box = fig.add_subplot(spec[0, 0])
    ax_hist = fig.add_subplot(spec[1, 0])
    ax_qqplot = fig.add_subplot(spec[:, 1])

    # Boxplot
    boxplot = sns.boxplot(data=df_temp, x=df_temp[var], showmeans=True, ax=ax_box,
                          meanprops={"markerfacecolor":"white", "markeredgecolor":"blue"})
    ax_box.set(xlabel="", xticks=[])
    ax_box.set(yticks=[])
    boxplot.set_title("")

    # Histplot
    sns.histplot(data=df_temp, x=df_temp[var], bins=75,  kde=True,  ax=ax_hist)
    if "SiteEnergyUse" in var:
        ax_hist.set(xlabel="kBtu")
    else:
        ax_hist.set(xlabel="MetricTonsCO2e")

    # QQplot
    qqplot(df_temp[var], line='s', ax=ax_qqplot)

    plt.savefig("img/qqplot-of-" + var + ".png")
    plt.show()

    print("\nMaking the Normality Test")
    print("---------------------------------")
    normality_test(df_temp[[var]])
    print("\n")

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">5.3 Multivariate Analysis</h4>
</div>
<br>
<div style="background-color: #6D83C5;" >
    <h5 style="margin: auto; padding: 20px; color:#fff; ">5.3.1 Correlation Matrix</h5>
</div>

In [ ]:
df_analysis(df_bebcs_log, "df_bebcs_log", type_analysis="complete")

In [ ]:
df_correlation_matrix = pd.DataFrame(df_bebcs_log.corr()).round(2)

In [ ]:
mask = np.zeros_like(df_correlation_matrix, dtype=bool)
mask[np.triu_indices_from(mask)] = True

In [ ]:
plt.figure(figsize=(16,6))
plt.title("Pearson correlation between all features", size=20)

ax = sns.heatmap(df_correlation_matrix, mask=mask, vmin=-1, cmap="mako_r",
                annot=True, annot_kws={"size": 14})

plt.xticks(rotation=25, size=14, horizontalalignment="right")
plt.yticks(rotation=0, size=14)
plt.tight_layout()
plt.savefig("img/pearson-correlation-between-features.png")
plt.show()

<div class="alert alert-block alert-success">
    <b>Observations / Conclusions</b>
    
        <ul style="list-style-type: square;">
            <li><b>Energy-kcal_100g</b> and <b>sugars_100g</b> have a strong direct relation with <b>nutriscore_score</b></li>
        </ul>               
</div>

<div style="background-color: #6D83C5;" >
    <h4 style="margin: auto; padding: 20px; color:#fff; ">5.4. Principal component analysis - PCA</h4>
</div>
<br>
<div class="alert alert-block alert-info">
    To make the PCA, we are are only going to work with the following features:
    <ul style="list-style-type: square;">
        <li>YearBuilt</li>
        <li>PropertyGFATotal</li>
        <li>NumberofFloors</li>
        <li>NumberofBuildings</li>
        <li>Electricity(kBtu)</li>
        <li>NaturalGas(kBtu)</li>
        <li>SiteEUI(kBtu/sf)</li>
        <li>SourceEUI(kBtu/sf)</li>
        <li>SteamUse(kBtu)</li>
    </ul>  
</div>

In [ ]:
TARGET_VARIABLES_LOG = [
    "SiteEnergyUse(kBtu)_log", "GHGEmissions(MetricTonsCO2e)_log"
]

In [ ]:
PCA_VARIABLES = [
    "YearBuilt", "PropertyGFATotal", "NumberofFloors", "NumberofBuildings", 
    "Electricity(kBtu)", "NaturalGas(kBtu)", "SiteEUI(kBtu/sf)", "SourceEUI(kBtu/sf)", 
    "SteamUse(kBtu)"
]

In [ ]:
OTHERS_VARIABLES = [
    "OSEBuildingID", "DataYear", "PrimaryPropertyType", "renamed_PrimaryPropertyType", 
    "ZipCode", "Neighborhood", 
]

<div class="alert alert-block alert-info">
    Considering only non missing-values
</div>

In [ ]:
df_subset = df_bebcs_log[df_bebcs_log[PCA_VARIABLES + TARGET_VARIABLES_LOG].notnull().all(axis=1)].copy()

In [ ]:
df_analysis(df_subset, "df_subset", type_analysis="complete")

<div class="alert alert-block alert-info">
   Numbers of components to calculate to PCA            
</div>

In [ ]:
n_comp = 6

<div class="alert alert-block alert-info">
    Selecting the features to analyse with PCA
</div>

In [ ]:
X = df_subset.loc[:, PCA_VARIABLES].values
index_values = df_subset.loc[:, PCA_VARIABLES].index
features = df_subset.loc[:, PCA_VARIABLES].columns

<div class="alert alert-block alert-info">
   Data standardization      
</div>

In [ ]:
X_scaled = StandardScaler().fit_transform(X)

<div class="alert alert-block alert-info">
   Principal components determination      
</div>

In [ ]:
pca = PCA(n_components=n_comp).fit(X_scaled)

In [ ]:
df_pca = pd.DataFrame(pca.components_, 
                      index=["PC" + str(i+1) for i in range(n_comp)],
                      columns=features ).T

In [ ]:
plt.figure(figsize=(10,5))
plt.title("Principal components coefficients", size=20)

ax = sns.heatmap(df_pca, vmin=-1, vmax=1, center=0, cmap="mako_r",
                annot=True, annot_kws={"size": 14})

plt.xticks(size=14)
plt.yticks(size=14)
plt.tight_layout()
plt.savefig("img/principal-components-coefficients.png")
plt.show()

<div class="alert alert-block alert-success">
    <b>Observations / Conclusions</b><br>
    
    In this graph we have the influence of each of the variables for each component
    
    <ul style="list-style-type: square;">
        <li><b>PC1</b> has a influence by <b>Electricity(kBtu)</b></li>
        <li><b>PC2</b> has a strong influence by <b>SiteEUI(kBtu/sf)</b> and <b>SourceEUI(kBtu/sf)</b></li>
        <li><b>PC3</b> has a strong influence by <b>NumberofBuildings</b></li>
        <li><b>PC4</b> has a strong influence by <b>NumberofBuildings</b> and <b>YearBuilt</b></li>
        <li><b>PC5</b> has a strong influence by <b>SteamUse(kBtu)</b> and <b>YearBuilt</b></li>
        <li><b>PC6</b> has a strong influence by <b>NaturalGas(kBtu)</b></li>
    </ul>     
</div>

<div class="alert alert-block alert-info">
    Plotting the <b>Scree of eigenvalues</b>
</div>

In [ ]:
scree = pca.explained_variance_ratio_*100

fig = plt.subplots(figsize=(10, 7))
plot_bar = sns.barplot(x=df_pca.columns, y=scree)
for p in plot_bar.patches:
    plot_bar.annotate(format(p.get_height(), ".1f"), (p.get_x() + p.get_width() / 2., p.get_height()), 
                    ha="center", va="bottom", xytext=(0, -15), textcoords="offset points", color="white")
plot_line = sns.lineplot(x=df_pca.columns, y=scree.cumsum(), marker="o", color="red")

for x, y in zip(df_pca.columns, scree.cumsum()):
    plot_line.text(x, y, "{:.2f}".format(y), ha="right", va="bottom")

plt.xlabel("Rank of the inertia axis", size=14)
plt.ylabel("% of inertia", size=14)
plt.title("Scree of eigenvalues", size=20)
plt.tight_layout()
plt.savefig("img/scree-of-eigenvalues.png")
plt.show()

<div class="alert alert-block alert-success">
    <b>Observations / Conclusions</b>
    
    <ul style="list-style-type: square;">
        <li>Up to <b>PC6</b>, we describe <b>95%</b> of the variance of the data. So, in this case we are going to take <b>all components</b></li>
    </ul>     
</div>
<div class="alert alert-block alert-info">
    <b>Keeping the 90% of the variance of the components</b>
</div>

In [ ]:
var_threshold=0.9

# Processing the PCA
pca = decomposition.PCA()
pca.fit(X_scaled)

# Getting the explained variance ratio for each principal component
scree = pca.explained_variance_ratio_

# Getting the number of principal components to reach variance thresholds
mask = scree.cumsum() > var_threshold
nb_selected_components = len(scree[~mask]) + 1
print("Number of selected components:", nb_selected_components)

# Compute and displays the actual ratio of explained variance
explained_variance_sum = scree.cumsum()[nb_selected_components-1]
print("Cumulative explained variance:  {:.2f}%".format(explained_variance_sum*100))

# Getting the projection of the data on the first components
X_PCA = pca.transform(X_scaled)[:,:nb_selected_components]

In [ ]:
df_worked = pd.DataFrame(data=X_PCA, columns=["PC1", "PC2", "PC3", "PC4", "PC5", "PC6"], index=index_values)

In [ ]:
df_worked.head(5)

In [ ]:
df_worked = pd.concat([df_worked, df_subset[OTHERS_VARIABLES], df_subset[TARGET_VARIABLES_LOG]], axis=1)

<div class="alert alert-block alert-info">
    Ordering the columns
</div>

In [ ]:
df_worked = df_worked[OTHERS_VARIABLES +
                      list(set(df_worked.columns) - set(OTHERS_VARIABLES + TARGET_VARIABLES_LOG)) +
                      TARGET_VARIABLES_LOG]

In [ ]:
df_worked.head(5)